/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 *
 * @param appLink
 * @param webUrl
 */
@Parcelize

data class DeepLink(
    @Json(name = "appLink")
    val appLink: kotlin.String? = null,
    @Json(name = "webUrl")
    val webUrl: kotlin.String? = null
) : Parcelable
