/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 *
 * @param severity
 * @param fromTime
 * @param title
 * @param description
 * @param toTime
 * @param eventId
 * @param affectedSchedules
 */
@Parcelize

data class Disruption(
    @Json(name = "severity")
    val severity: DisruptionSeverity,
    @Json(name = "fromTime")
    val fromTime: kotlin.String,
    @Json(name = "title")
    val title: kotlin.String? = null,
    @Json(name = "description")
    val description: kotlin.String? = null,
    @Json(name = "toTime")
    val toTime: kotlin.String? = null,
    @Json(name = "eventId")
    val eventId: kotlin.String? = null,
    @Json(name = "affectedSchedules")
    val affectedSchedules: kotlin.collections.List<AffectedSchedule>? = null
) : Parcelable
