/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json

/**
*
* Values: NOT_AFFECTED,INFORMATION,WARNING,ALERT
*/

enum class DisruptionSeverity(val value: kotlin.String) {

    @Json(name = "NOT_AFFECTED")
    NOT_AFFECTED("NOT_AFFECTED"),

    @Json(name = "INFORMATION")
    INFORMATION("INFORMATION"),

    @Json(name = "WARNING")
    WARNING("WARNING"),

    @Json(name = "ALERT")
    ALERT("ALERT");
}
