/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 *
 * @param scannerScreenTitle
 * @param scannerScreenNoPermissionText
 * @param openManualNumberInputButtonTitle
 * @param manualNumberScreenTitle
 * @param manualNumberInputLabelText
 * @param manualNumberInputWhereToFindText
 * @param manualNumberInputConfirmIdButtonTitle
 */
@Parcelize

data class InstantUnlockData(
    @Json(name = "scannerScreenTitle")
    val scannerScreenTitle: kotlin.String,
    @Json(name = "scannerScreenNoPermissionText")
    val scannerScreenNoPermissionText: kotlin.String,
    @Json(name = "openManualNumberInputButtonTitle")
    val openManualNumberInputButtonTitle: kotlin.String,
    @Json(name = "manualNumberScreenTitle")
    val manualNumberScreenTitle: kotlin.String,
    @Json(name = "manualNumberInputLabelText")
    val manualNumberInputLabelText: kotlin.String,
    @Json(name = "manualNumberInputWhereToFindText")
    val manualNumberInputWhereToFindText: kotlin.String,
    @Json(name = "manualNumberInputConfirmIdButtonTitle")
    val manualNumberInputConfirmIdButtonTitle: kotlin.String
) : Parcelable
