/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 *
 * @param coordinate
 * @param name
 * @param address
 */
@Parcelize

data class Location(
    @Json(name = "coordinate")
    val coordinate: LatLng,
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "address")
    val address: kotlin.String? = null
) : Parcelable
