/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 *
 * @param name
 * @param value
 * @param description
 */
@Parcelize

data class Pin(
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "value")
    val value: kotlin.String,
    @Json(name = "description")
    val description: kotlin.String? = null
) : Parcelable
