/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 *
 * @param id
 * @param name
 * @param color
 * @param isLevel3
 * @param transportIcon
 * @param wheelchairAccessible
 * @param idPrefix
 * @param accentColor
 * @param icon
 * @param supportInfo
 * @param faq
 * @param howItWorks
 * @param sharingPricing
 * @param instantUnlockData
 * @param sharingOptions
 */
@Parcelize

data class Provider(
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "color")
    val color: kotlin.String,
    @Json(name = "isLevel3")
    val isLevel3: kotlin.Boolean,
    @Json(name = "transportIcon")
    val transportIcon: kotlin.String,
    @Json(name = "wheelchairAccessible")
    val wheelchairAccessible: kotlin.Boolean,
    @Json(name = "idPrefix")
    val idPrefix: kotlin.String? = null,
    @Json(name = "accentColor")
    val accentColor: kotlin.String? = null,
    @Json(name = "icon")
    val icon: kotlin.String? = null,
    @Json(name = "supportInfo")
    val supportInfo: SupportInfo? = null,
    @Json(name = "faq")
    val faq: Faq? = null,
    @Json(name = "howItWorks")
    val howItWorks: HowItWorks? = null,
    @Json(name = "sharingPricing")
    val sharingPricing: VehiclePricing? = null,
    @Json(name = "instantUnlockData")
    val instantUnlockData: InstantUnlockData? = null,
    @Json(name = "sharingOptions")
    val sharingOptions: kotlin.collections.List<SharingProviderOptions>? = null
) : Parcelable
