/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 *
 * @param schedule
 * @param track
 * @param stops
 * @param alternatives
 * @param providerId
 * @param exactDeparture
 * @param intervalDeparture
 */
@Parcelize

data class RouteSegmentTransit(
    @Json(name = "schedule")
    val schedule: Schedule,
    @Json(name = "track")
    val track: Track,
    @Json(name = "stops")
    val stops: kotlin.collections.List<RouteSegmentStop>,
    @Json(name = "alternatives")
    val alternatives: kotlin.collections.List<TransitAlternative>,
    @Json(name = "providerId")
    val providerId: kotlin.String? = null,
    @Json(name = "exactDeparture")
    val exactDeparture: RouteExactDeparture? = null,
    @Json(name = "intervalDeparture")
    val intervalDeparture: RouteIntervalDeparture? = null
) : Parcelable
