/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 *
 * @param id
 * @param segments
 * @param startTime
 * @param endTime
 * @param duration
 * @param isAvailable
 * @param firstTransitSegmentExactDepartures
 * @param groupId
 * @param fare
 * @param labelKey
 * @param disruption
 */
@Parcelize

data class Route(
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "segments")
    val segments: kotlin.collections.List<RouteSegment>,
    @Json(name = "startTime")
    val startTime: kotlin.String,
    @Json(name = "endTime")
    val endTime: kotlin.String,
    @Json(name = "duration")
    val duration: Duration,
    @Json(name = "isAvailable")
    val isAvailable: kotlin.Boolean,
    @Json(name = "firstTransitSegmentExactDepartures")
    val firstTransitSegmentExactDepartures: kotlin.collections.List<RouteExactDeparture>,
    @Json(name = "groupId")
    val groupId: kotlin.String? = null,
    @Json(name = "fare")
    val fare: RouteFare? = null,
    @Json(name = "labelKey")
    val labelKey: kotlin.String? = null,
    @Json(name = "disruption")
    val disruption: RouteDisruption? = null
) : Parcelable
