/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 *
 * @param severity
 * @param disruptions
 * @param title
 */
@Parcelize

data class RouteDisruption(
    @Json(name = "severity")
    val severity: DisruptionSeverity,
    @Json(name = "disruptions")
    val disruptions: kotlin.collections.List<Disruption>,
    @Json(name = "title")
    val title: kotlin.String? = null
) : Parcelable
