/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 *
 * @param id
 * @param mode
 * @param start
 * @param end
 * @param startTime
 * @param endTime
 * @param shape Shape, or path, of the segment, encoded using Google polyline encoding format !:https://developers.google.com/maps/documentation/utilities/polylinealgorithm
 * @param transit
 * @param walking
 * @param sharing
 * @param rideHailing
 * @param fareId
 * @param disruption
 */
@Parcelize

data class RouteSegment(
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "mode")
    val mode: RouteSegmentMode,
    @Json(name = "start")
    val start: Location,
    @Json(name = "end")
    val end: Location,
    @Json(name = "startTime")
    val startTime: kotlin.String,
    @Json(name = "endTime")
    val endTime: kotlin.String,
    /* Shape, or path, of the segment, encoded using Google polyline encoding format !:https://developers.google.com/maps/documentation/utilities/polylinealgorithm */
    @Json(name = "shape")
    val shape: kotlin.String,
    @Json(name = "transit")
    val transit: RouteSegmentTransit? = null,
    @Json(name = "walking")
    val walking: RouteSegmentWalking? = null,
    @Json(name = "sharing")
    val sharing: RouteSegmentSharing? = null,
    @Json(name = "rideHailing")
    val rideHailing: RouteSegmentRideHailing? = null,
    @Json(name = "fareId")
    val fareId: kotlin.String? = null,
    @Json(name = "disruption")
    val disruption: RouteSegmentDisruption? = null
) : Parcelable
