/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 *
 * @param id
 * @param name
 * @param vehicleType
 * @param location
 * @param address
 * @param freeSpots
 * @param vehicleCount
 */
@Parcelize

data class RouteSegmentSharingStation(
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "vehicleType")
    val vehicleType: VehicleType,
    @Json(name = "location")
    val location: LatLng,
    @Json(name = "address")
    val address: kotlin.String? = null,
    @Json(name = "freeSpots")
    val freeSpots: kotlin.Int? = null,
    @Json(name = "vehicleCount")
    val vehicleCount: kotlin.Int? = null
) : Parcelable
