/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 *
 * @param id
 * @param name Line number/name
 * @param color
 * @param transport
 * @param transportId
 * @param longName
 * @param transportType
 */
@Parcelize

data class Schedule(
    @Json(name = "id")
    val id: kotlin.String,
    /* Line number/name */
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "color")
    val color: kotlin.String,
    @Json(name = "transport")
    val transport: Transport,
    @Json(name = "transportId")
    val transportId: kotlin.String,
    @Json(name = "longName")
    val longName: kotlin.String? = null,
    @Json(name = "transportType")
    val transportType: kotlin.String? = null
) : Parcelable
