/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 *
 * @param vehicleType
 * @param transportIcon
 * @param hasStations
 * @param vehicleSubtype
 * @param instantUnlockData
 * @param booking
 * @param vehicleSelection
 */
@Parcelize

data class SharingProviderOptions(
    @Json(name = "vehicleType")
    val vehicleType: VehicleType,
    @Json(name = "transportIcon")
    val transportIcon: kotlin.String,
    @Json(name = "hasStations")
    val hasStations: kotlin.Boolean,
    @Json(name = "vehicleSubtype")
    val vehicleSubtype: kotlin.String? = null,
    @Json(name = "instantUnlockData")
    val instantUnlockData: InstantUnlockData? = null,
    @Json(name = "booking")
    val booking: SharingBookingOptions? = null,
    @Json(name = "vehicleSelection")
    val vehicleSelection: SharingVehicleSelectionOptions? = null
) : Parcelable
