/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json

/**
*
* Values: RESERVED,LEASED,FINISHED,CANCELED,PAUSED
*/

enum class SharingBookingStatus(val value: kotlin.String) {

    @Json(name = "RESERVED")
    RESERVED("RESERVED"),

    @Json(name = "LEASED")
    LEASED("LEASED"),

    @Json(name = "FINISHED")
    FINISHED("FINISHED"),

    @Json(name = "CANCELED")
    CANCELED("CANCELED"),

    @Json(name = "PAUSED")
    PAUSED("PAUSED");
}
