/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 *
 * @param id
 * @param providerId
 * @param location
 * @param tags
 * @param endLeaseSupported
 * @param reservationSupported
 * @param parkingSupported
 * @param requiresUserLocation
 * @param type
 * @param stationId
 * @param name
 * @param address
 * @param licencePlate
 * @param pricing
 * @param imageUrl
 * @param battery
 * @param fuel
 * @param rangeRemaining
 * @param deepLinkIos
 * @param deepLinkAndroid
 * @param localizations
 * @param pin
 * @param subtype
 */
@Parcelize

data class SharedVehicle(
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "providerId")
    val providerId: kotlin.String,
    @Json(name = "location")
    val location: LatLng,
    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>,
    @Json(name = "endLeaseSupported")
    val endLeaseSupported: kotlin.Boolean,
    @Json(name = "reservationSupported")
    val reservationSupported: kotlin.Boolean,
    @Json(name = "parkingSupported")
    val parkingSupported: kotlin.Boolean,
    @Json(name = "requiresUserLocation")
    val requiresUserLocation: kotlin.Boolean,
    @Json(name = "type")
    val type: VehicleType,
    @Json(name = "stationId")
    val stationId: kotlin.String? = null,
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "address")
    val address: kotlin.String? = null,
    @Json(name = "licencePlate")
    val licencePlate: kotlin.String? = null,
    @Json(name = "pricing")
    val pricing: VehiclePricing? = null,
    @Json(name = "imageUrl")
    val imageUrl: kotlin.String? = null,
    @Json(name = "battery")
    val battery: Battery? = null,
    @Json(name = "fuel")
    val fuel: Fuel? = null,
    @Json(name = "rangeRemaining")
    val rangeRemaining: kotlin.Int? = null,
    @Json(name = "deepLinkIos")
    val deepLinkIos: DeepLink? = null,
    @Json(name = "deepLinkAndroid")
    val deepLinkAndroid: DeepLink? = null,
    @Json(name = "localizations")
    val localizations: VehicleSharingLocalizations? = null,
    @Json(name = "pin")
    val pin: Pin? = null,
    @Json(name = "subtype")
    val subtype: kotlin.String? = null
) : Parcelable
