/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 *
 * @param id
 * @param name
 * @param regionId
 * @param location
 * @param type
 * @param exits
 * @param transports
 * @param transportIds
 * @param address
 * @param direction
 * @param parentId
 * @param zoneId
 */
@Parcelize

data class Stop(
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "regionId")
    val regionId: kotlin.String,
    @Json(name = "location")
    val location: LatLng,
    @Json(name = "type")
    val type: StopType,
    @Json(name = "exits")
    val exits: kotlin.collections.List<Stop>,
    @Json(name = "transports")
    val transports: kotlin.collections.List<Transport>,
    @Json(name = "transportIds")
    val transportIds: kotlin.collections.List<kotlin.String>,
    @Json(name = "address")
    val address: kotlin.String? = null,
    @Json(name = "direction")
    val direction: kotlin.String? = null,
    @Json(name = "parentId")
    val parentId: kotlin.String? = null,
    @Json(name = "zoneId")
    val zoneId: kotlin.String? = null
) : Parcelable
