/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json

/**
*
* Values: UNKNOWN,FORWARD,BACKWARD
*/

enum class TrackDirection(val value: kotlin.String) {

    @Json(name = "UNKNOWN")
    UNKNOWN("UNKNOWN"),

    @Json(name = "FORWARD")
    FORWARD("FORWARD"),

    @Json(name = "BACKWARD")
    BACKWARD("BACKWARD");
}
