/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 *
 * @param id
 * @param destination
 * @param name
 * @param shape
 * @param direction
 * @param visible
 */
@Parcelize

data class Track(
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "destination")
    val destination: kotlin.String,
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "shape")
    val shape: kotlin.String,
    @Json(name = "direction")
    val direction: TrackDirection,
    @Json(name = "visible")
    val visible: kotlin.Boolean
) : Parcelable
