/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 *
 * @param loginAndReserveButtonTitle
 * @param reserveButtonTitle
 * @param reservingButtonTitle
 * @param startLeaseButtonTitle
 * @param startingLeaseButtonTitle
 * @param startLeaseConfirmationTitle
 * @param startLeaseConfirmationButtonTitle
 * @param endLeaseButtonTitle
 * @param endingLeaseButtonTitle
 * @param endLeaseConfirmationTitle
 * @param endLeaseConfirmationButtonTitle
 * @param startedLeaseInfoTitle
 * @param startedLeaseInfoBody
 * @param startedLeaseInformationTitle
 */
@Parcelize

data class VehicleSharingLocalizations(
    @Json(name = "loginAndReserveButtonTitle")
    val loginAndReserveButtonTitle: kotlin.String,
    @Json(name = "reserveButtonTitle")
    val reserveButtonTitle: kotlin.String,
    @Json(name = "reservingButtonTitle")
    val reservingButtonTitle: kotlin.String,
    @Json(name = "startLeaseButtonTitle")
    val startLeaseButtonTitle: kotlin.String,
    @Json(name = "startingLeaseButtonTitle")
    val startingLeaseButtonTitle: kotlin.String,
    @Json(name = "startLeaseConfirmationTitle")
    val startLeaseConfirmationTitle: kotlin.String,
    @Json(name = "startLeaseConfirmationButtonTitle")
    val startLeaseConfirmationButtonTitle: kotlin.String,
    @Json(name = "endLeaseButtonTitle")
    val endLeaseButtonTitle: kotlin.String,
    @Json(name = "endingLeaseButtonTitle")
    val endingLeaseButtonTitle: kotlin.String,
    @Json(name = "endLeaseConfirmationTitle")
    val endLeaseConfirmationTitle: kotlin.String,
    @Json(name = "endLeaseConfirmationButtonTitle")
    val endLeaseConfirmationButtonTitle: kotlin.String,
    @Json(name = "startedLeaseInfoTitle")
    val startedLeaseInfoTitle: kotlin.String? = null,
    @Json(name = "startedLeaseInfoBody")
    val startedLeaseInfoBody: kotlin.String? = null,
    @Json(name = "startedLeaseInformationTitle")
    val startedLeaseInformationTitle: kotlin.String? = null
) : Parcelable
