/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json

/**
*
* Values: UNKNOWN,CAR,SCOOTER,BIKE,KICK_SCOOTER
*/

enum class VehicleType(val value: kotlin.String) {

    @Json(name = "UNKNOWN")
    UNKNOWN("UNKNOWN"),

    @Json(name = "CAR")
    CAR("CAR"),

    @Json(name = "SCOOTER")
    SCOOTER("SCOOTER"),

    @Json(name = "BIKE")
    BIKE("BIKE"),

    @Json(name = "KICK_SCOOTER")
    KICK_SCOOTER("KICK_SCOOTER");
}
