/**
* Core Whitelabel API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.trafi.core.model

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 *
 * @param distance
 * @param start
 * @param end
 * @param startTime
 * @param endTime
 * @param shape
 * @param walkType
 */
@Parcelize

data class WalkingPath(
    @Json(name = "distance")
    val distance: Distance,
    @Json(name = "start")
    val start: Location,
    @Json(name = "end")
    val end: Location,
    @Json(name = "startTime")
    val startTime: kotlin.String,
    @Json(name = "endTime")
    val endTime: kotlin.String,
    @Json(name = "shape")
    val shape: kotlin.String,
    @Json(name = "walkType")
    val walkType: WalkType
) : Parcelable
