/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param color
 * @param icon
 * @param title
 * @param isAvailable
 * @param accentColor
 */
@Serializable
data class AccountActivationItem(

    @SerialName(value = "color") @Required val color: kotlin.String,

    @SerialName(value = "icon") @Required val icon: kotlin.String,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "isAvailable") @Required val isAvailable: kotlin.Boolean,

    @SerialName(value = "accentColor") val accentColor: kotlin.String? = null

)
