/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param distance
 * @param endsWithEntrance
 * @param startsWithExit
 * @param start
 * @param end
 * @param startTime
 * @param endTime
 * @param walkingPath
 * @param platformPath
 * @param departure
 * @param duration
 */
@Serializable
data class ActiveTripStepWalking(

    @SerialName(value = "distance") @Required val distance: Distance,

    @SerialName(value = "endsWithEntrance") @Required val endsWithEntrance: kotlin.Boolean,

    @SerialName(value = "startsWithExit") @Required val startsWithExit: kotlin.Boolean,

    @SerialName(value = "start") @Required val start: Location,

    @SerialName(value = "end") @Required val end: Location,

    @SerialName(value = "startTime") @Required val startTime: kotlin.String,

    @SerialName(value = "endTime") @Required val endTime: kotlin.String,

    @SerialName(value = "walkingPath") val walkingPath: Path? = null,

    @SerialName(value = "platformPath") val platformPath: Path? = null,

    @SerialName(value = "departure") val departure: ActiveTripTransitDeparture? = null,

    @SerialName(value = "duration") val duration: Duration? = null

)
