/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param activeTripId
 * @param steps
 * @param startTime
 * @param endTime
 * @param duration
 * @param activeStepIndex Active step index will be null, until first not null user location.
 */
@Serializable
data class ActiveTripSteps(

    @SerialName(value = "activeTripId") @Required val activeTripId: kotlin.String,

    @SerialName(value = "steps") @Required val steps: kotlin.collections.List<ActiveTripStep>,

    @SerialName(value = "startTime") @Required val startTime: kotlin.String,

    @SerialName(value = "endTime") @Required val endTime: kotlin.String,

    @SerialName(value = "duration") @Required val duration: Duration,

    /* Active step index will be null, until first not null user location. */
    @SerialName(value = "activeStepIndex") val activeStepIndex: kotlin.Int? = null

)
