/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param ticketId
 * @param count
 * @param departureStopId
 * @param idempotencyKey
 * @param providerId
 */
@Serializable
data class ActivateTicketRequest(

    @SerialName(value = "ticketId") @Required val ticketId: kotlin.String,

    @SerialName(value = "count") @Required val count: kotlin.Int,

    @SerialName(value = "departureStopId") val departureStopId: kotlin.String? = null,

    @SerialName(value = "idempotencyKey") val idempotencyKey: kotlin.String? = null,

    @SerialName(value = "providerId") val providerId: kotlin.String? = null

)
