/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param location
 * @param accuracy
 * @param altitude
 * @param bearing
 * @param speed
 * @param time
 */
@Serializable
data class ActiveTripLogEntry(

    @SerialName(value = "location") @Required val location: LatLng,

    @SerialName(value = "accuracy") @Required val accuracy: kotlin.Double,

    @SerialName(value = "altitude") @Required val altitude: kotlin.Double,

    @SerialName(value = "bearing") @Required val bearing: kotlin.Double,

    @SerialName(value = "speed") @Required val speed: kotlin.Double,

    @SerialName(value = "time") @Required val time: kotlin.Long

)
