/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param schedule
 * @param destination
 * @param time
 * @param isRealtime
 * @param tags
 * @param duration
 */
@Serializable
data class ActiveTripTransitDeparture(

    @SerialName(value = "schedule") @Required val schedule: Schedule,

    @SerialName(value = "destination") @Required val destination: kotlin.String,

    @SerialName(value = "time") @Required val time: kotlin.String,

    @SerialName(value = "isRealtime") @Required val isRealtime: kotlin.Boolean,

    @SerialName(value = "tags") @Required val tags: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "duration") @Required val duration: Duration

)
