/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param title
 * @param transit
 * @param walking
 * @param transitWaiting
 * @param finished
 */
@Serializable
data class ActiveTripStep(

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "transit") val transit: ActiveTripStepTransit? = null,

    @SerialName(value = "walking") val walking: ActiveTripStepWalking? = null,

    @SerialName(value = "transitWaiting") val transitWaiting: ActiveTripStepTransitWaiting? = null,

    @SerialName(value = "finished") val finished: ActiveTripStepFinished? = null

)
