/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param activeTripId
 * @param stepIndex
 * @param categoryId
 * @param comment
 * @param log
 */
@Serializable
data class ActiveTripStepFeedback(

    @SerialName(value = "activeTripId") @Required val activeTripId: kotlin.String,

    @SerialName(value = "stepIndex") @Required val stepIndex: kotlin.Int,

    @SerialName(value = "categoryId") @Required val categoryId: kotlin.String,

    @SerialName(value = "comment") val comment: kotlin.String? = null,

    @SerialName(value = "log") val log: ActiveTripLogEntry? = null

)
