/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param encryptedPaymentMethod
 * @param paymentMethodType
 * @param paymentMethodOrigin
 * @param braintreeDeviceData
 */
@Serializable
data class AddPaymentMethodRequest(

    @SerialName(value = "encryptedPaymentMethod") @Required val encryptedPaymentMethod: kotlin.String,

    @SerialName(value = "paymentMethodType") @Required val paymentMethodType: PaymentMethodType,

    @SerialName(value = "paymentMethodOrigin") val paymentMethodOrigin: PaymentMethodOrigin? = null,

    @SerialName(value = "braintreeDeviceData") val braintreeDeviceData: kotlin.String? = null

)
