/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param accessToken
 * @param refreshToken
 * @param accessTokenExpiresAt
 * @param refreshTokenExpiresAt
 */
@Serializable
data class AuthData(

    @SerialName(value = "accessToken") @Required val accessToken: kotlin.String,

    @SerialName(value = "refreshToken") @Required val refreshToken: kotlin.String,

    @SerialName(value = "accessTokenExpiresAt") @Required val accessTokenExpiresAt: kotlin.String,

    @SerialName(value = "refreshTokenExpiresAt") val refreshTokenExpiresAt: kotlin.String? = null

)
