/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param code Authorization code
 * @param verifier PKCE verifier related to the code challenge sent when retrieving authorization code
 * @param redirectUrl
 */
@Serializable
data class AuthCodeRequest(

    /* Authorization code */
    @SerialName(value = "code") @Required val code: kotlin.String,

    /* PKCE verifier related to the code challenge sent when retrieving authorization code */
    @SerialName(value = "verifier") val verifier: kotlin.String? = null,

    @SerialName(value = "redirectUrl") val redirectUrl: kotlin.String? = null

)
