/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param sharingBookings
 * @param rentalBookings
 * @param rideHailingBookings
 * @param activeTickets
 * @param currentTime
 * @param errors
 */
@Serializable
data class BookingsResponseV1(

    @SerialName(value = "sharingBookings") @Required val sharingBookings: kotlin.collections.List<SharingBooking>,

    @SerialName(value = "rentalBookings") @Required val rentalBookings: kotlin.collections.List<RentalBooking>,

    @SerialName(value = "rideHailingBookings") @Required val rideHailingBookings: kotlin.collections.List<RideHailingBooking>,

    @SerialName(value = "activeTickets") @Required val activeTickets: kotlin.collections.List<ActiveTickets>,

    @SerialName(value = "currentTime") @Required val currentTime: kotlin.Long,

    @SerialName(value = "errors") @Required val errors: kotlin.collections.List<Error>

)
