/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param cancelationFeeText Warning for the user if a fee might be applied for canceling the booking
 */
@Serializable
data class BookingFeeInfo(

    /* Warning for the user if a fee might be applied for canceling the booking */
    @SerialName(value = "cancelationFeeText") val cancelationFeeText: kotlin.String? = null

)
