/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param info
 * @param currency
 * @param price
 * @param purchasedAt
 * @param code
 */
@Serializable
data class BoughtItem(

    @SerialName(value = "info") @Required val info: ProductInfo,

    @SerialName(value = "currency") @Required val currency: kotlin.String,

    @SerialName(value = "price") @Required val price: kotlin.Double,

    @SerialName(value = "purchasedAt") @Required val purchasedAt: kotlin.String,

    @SerialName(value = "code") val code: kotlin.String? = null

)
