/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param brandAndModel
 * @param plateNumber
 * @param bearing
 * @param latLng
 * @param pictureUrl
 */
@Serializable
data class Car(

    @SerialName(value = "brandAndModel") @Required val brandAndModel: kotlin.String,

    @SerialName(value = "plateNumber") @Required val plateNumber: kotlin.String,

    @SerialName(value = "bearing") @Required val bearing: kotlin.Double,

    @SerialName(value = "latLng") val latLng: LatLng? = null,

    @SerialName(value = "pictureUrl") val pictureUrl: kotlin.String? = null

)
