/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param phoneNumber
 * @param code
 * @param confirmationContext
 */
@Serializable
data class ConfirmOtpAuthenticationRequest(

    @SerialName(value = "phoneNumber") @Required val phoneNumber: kotlin.String,

    @SerialName(value = "code") @Required val code: kotlin.String,

    @SerialName(value = "confirmationContext") @Required val confirmationContext: kotlin.String

)
