/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param authData
 * @param user
 * @param challenge
 */
@Serializable
data class ConfirmOtpAuthenticationResponse(

    @SerialName(value = "authData") val authData: AuthData? = null,

    @SerialName(value = "user") val user: User? = null,

    @SerialName(value = "challenge") val challenge: OtpAuthenticationChallenge? = null

)
