/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param buttonTitle
 * @param title
 * @param body
 * @param notes
 */
@Serializable
data class ConnectionLocalizations(

    @SerialName(value = "buttonTitle") @Required val buttonTitle: kotlin.String,

    @SerialName(value = "title") val title: kotlin.String? = null,

    @SerialName(value = "body") val body: kotlin.String? = null,

    @SerialName(value = "notes") val notes: kotlin.String? = null

)
