/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param requestContext
 * @param surgeInfo
 * @param booking
 */
@Serializable
data class CreateRideHailingBookingResponse(

    @SerialName(value = "requestContext") val requestContext: kotlin.String? = null,

    @SerialName(value = "surgeInfo") val surgeInfo: SurgeInfo? = null,

    @SerialName(value = "booking") val booking: RideHailingBooking? = null

)
