/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param stationAvailabilityId
 * @param trip
 * @param initialBookingStatus
 * @param paymentMethodId
 * @param tripPurposeId
 * @param providerPaymentMethodId
 * @param messagingToken
 * @param coordinates
 * @param braintreeDeviceData
 */
@Serializable
data class CreateRentalBookingRequest(

    @SerialName(value = "stationAvailabilityId") @Required val stationAvailabilityId: kotlin.String,

    @SerialName(value = "trip") @Required val trip: RentalBookingTrip,

    @SerialName(value = "initialBookingStatus") val initialBookingStatus: RentalBookingStatus? = null,

    @SerialName(value = "paymentMethodId") val paymentMethodId: kotlin.String? = null,

    @SerialName(value = "tripPurposeId") val tripPurposeId: kotlin.String? = null,

    @SerialName(value = "providerPaymentMethodId") val providerPaymentMethodId: kotlin.String? = null,

    @SerialName(value = "messagingToken") val messagingToken: kotlin.String? = null,

    @SerialName(value = "coordinates") val coordinates: LatLng? = null,

    @SerialName(value = "braintreeDeviceData") val braintreeDeviceData: kotlin.String? = null

)
