/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param providerId
 * @param productId
 * @param requestContext
 * @param providerPaymentMethodId
 * @param paymentMethodId
 * @param tripPurposeId
 * @param messagingToken
 * @param braintreeDeviceData
 */
@Serializable
data class CreateRideHailingBookingRequest(

    @SerialName(value = "providerId") @Required val providerId: kotlin.String,

    @SerialName(value = "productId") @Required val productId: kotlin.String,

    @SerialName(value = "requestContext") @Required val requestContext: kotlin.String,

    @SerialName(value = "providerPaymentMethodId") val providerPaymentMethodId: kotlin.String? = null,

    @SerialName(value = "paymentMethodId") val paymentMethodId: kotlin.String? = null,

    @SerialName(value = "tripPurposeId") val tripPurposeId: kotlin.String? = null,

    @SerialName(value = "messagingToken") val messagingToken: kotlin.String? = null,

    @SerialName(value = "braintreeDeviceData") val braintreeDeviceData: kotlin.String? = null

)
