/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param paymentTitle
 * @param paymentSubtitle
 * @param expirationDate
 * @param lastNumbers
 * @param cardType
 * @param title
 * @param cardTypeName
 */
@Serializable
data class CreditCardInfo(

    @SerialName(value = "paymentTitle") @Required val paymentTitle: kotlin.String,

    @SerialName(value = "paymentSubtitle") @Required val paymentSubtitle: kotlin.String,

    @SerialName(value = "expirationDate") val expirationDate: kotlin.String? = null,

    @SerialName(value = "lastNumbers") val lastNumbers: kotlin.String? = null,

    @SerialName(value = "cardType") val cardType: kotlin.String? = null,

    @SerialName(value = "title") val title: kotlin.String? = null,

    @SerialName(value = "cardTypeName") val cardTypeName: kotlin.String? = null

)
