/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param severity
 * @param fromTime
 * @param title
 * @param description
 * @param toTime
 * @param eventId
 * @param affectedSchedules
 */
@Serializable
data class Disruption(

    @SerialName(value = "severity") @Required val severity: DisruptionSeverity,

    @SerialName(value = "fromTime") @Required val fromTime: kotlin.String,

    @SerialName(value = "title") val title: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "toTime") val toTime: kotlin.String? = null,

    @SerialName(value = "eventId") val eventId: kotlin.String? = null,

    @SerialName(value = "affectedSchedules") val affectedSchedules: kotlin.collections.List<AffectedSchedule>? = null

)
