/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param category
 * @param issuedAt
 * @param expiresAt
 */
@Serializable
data class DrivingLicenceCategory(

    @SerialName(value = "category") val category: kotlin.String? = null,

    @SerialName(value = "issuedAt") val issuedAt: kotlin.String? = null,

    @SerialName(value = "expiresAt") val expiresAt: kotlin.String? = null

)
