/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param name
 * @param rating
 * @param phoneNumber
 * @param smsNumber
 * @param pictureUrl
 */
@Serializable
data class Driver(

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "rating") val rating: Rating? = null,

    @SerialName(value = "phoneNumber") val phoneNumber: kotlin.String? = null,

    @SerialName(value = "smsNumber") val smsNumber: kotlin.String? = null,

    @SerialName(value = "pictureUrl") val pictureUrl: kotlin.String? = null

)
