/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param developerMessage
 * @param errorCode
 * @param message
 * @param analyticsId
 * @param traceId
 * @param providerWithRequirements
 */
@Serializable
data class Error(

    @SerialName(value = "developerMessage") val developerMessage: kotlin.String? = null,

    @SerialName(value = "errorCode") val errorCode: kotlin.String? = null,

    @SerialName(value = "message") val message: kotlin.String? = null,

    @SerialName(value = "analyticsId") val analyticsId: kotlin.String? = null,

    @SerialName(value = "traceId") val traceId: kotlin.String? = null,

    @SerialName(value = "providerWithRequirements") val providerWithRequirements: ProviderWithRequirements? = null

)
