/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param time
 * @param isRealtime
 * @param tags
 * @param tripId
 * @param destination
 * @param platformCode
 * @param platformName
 * @param disruption
 */
@Serializable
data class ExactDeparture(

    @SerialName(value = "time") @Required val time: kotlin.String,

    @SerialName(value = "isRealtime") @Required val isRealtime: kotlin.Boolean,

    @SerialName(value = "tags") @Required val tags: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "tripId") val tripId: kotlin.String? = null,

    @SerialName(value = "destination") val destination: kotlin.String? = null,

    @SerialName(value = "platformCode") val platformCode: kotlin.String? = null,

    @SerialName(value = "platformName") val platformName: kotlin.String? = null,

    @SerialName(value = "disruption") val disruption: DepartureDisruption? = null

)
