/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param redirectUrlCancel
 * @param redirectUrlSuccess
 * @param redirectUrlPending
 * @param redirectUrlFailure
 * @param type
 * @param origin
 */
@Serializable
data class ExternalInitiateAddPaymentMethodRequest(

    @SerialName(value = "redirectUrlCancel") @Required val redirectUrlCancel: kotlin.String,

    @SerialName(value = "redirectUrlSuccess") @Required val redirectUrlSuccess: kotlin.String,

    @SerialName(value = "redirectUrlPending") val redirectUrlPending: kotlin.String? = null,

    @SerialName(value = "redirectUrlFailure") val redirectUrlFailure: kotlin.String? = null,

    @SerialName(value = "type") val type: PaymentMethodType? = null,

    @SerialName(value = "origin") val origin: PaymentMethodOrigin? = null

)
