/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param titleText
 * @param availableItems
 * @param type
 * @param icon
 * @param subtitleText
 * @param defaultItemIds
 * @param explanation
 */
@Serializable
data class Filter(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "titleText") @Required val titleText: kotlin.String,

    @SerialName(value = "availableItems") @Required val availableItems: kotlin.collections.List<RentalFilterItem>,

    @SerialName(value = "type") @Required val type: FilterType,

    @SerialName(value = "icon") val icon: kotlin.String? = null,

    @SerialName(value = "subtitleText") val subtitleText: kotlin.String? = null,

    @SerialName(value = "defaultItemIds") val defaultItemIds: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "explanation") val explanation: kotlin.String? = null

)
