/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param route
 * @param routeSearchResponseId
 * @param user
 */
@Serializable
data class GetActiveTripStepsRequest(

    @SerialName(value = "route") @Required val route: Route,

    @SerialName(value = "routeSearchResponseId") val routeSearchResponseId: kotlin.String? = null,

    @SerialName(value = "user") val user: LatLng? = null

)
