/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * for one way travel, outbound.  For bidirectional travel, there are two cases - a one return or two singles - outbound + inbound.
 *
 * @param providers
 * @param inboundCategories
 * @param outboundCategories
 * @param returnCategories
 */
@Serializable
data class GetProductsByRouteResponse(

    @SerialName(value = "providers") @Required val providers: kotlin.collections.List<Provider>,

    @SerialName(value = "inboundCategories") @Required val inboundCategories: kotlin.collections.List<TicketProductCategory>,

    @SerialName(value = "outboundCategories") @Required val outboundCategories: kotlin.collections.List<TicketProductCategory>,

    @SerialName(value = "returnCategories") @Required val returnCategories: kotlin.collections.List<TicketProductCategory>

)
