/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param startStop
 * @param endStop
 * @param startTimeMillis UTC time in millis
 * @param providerIds
 * @param returnTimeMillis UTC time in millis
 * @param passengerCount
 * @param filters filter/hints for product list. for example - class:1, fare:child, direction: single.
 */
@Serializable
data class GetProductsByRouteRequest(

    @SerialName(value = "startStop") @Required val startStop: RouteStop,

    @SerialName(value = "endStop") @Required val endStop: RouteStop,

    /* UTC time in millis */
    @SerialName(value = "startTimeMillis") @Required val startTimeMillis: kotlin.Long,

    @SerialName(value = "providerIds") val providerIds: kotlin.collections.List<kotlin.String>? = null,

    /* UTC time in millis */
    @SerialName(value = "returnTimeMillis") val returnTimeMillis: kotlin.Long? = null,

    @SerialName(value = "passengerCount") val passengerCount: kotlin.Int? = null,

    /* filter/hints for product list. for example - class:1, fare:child, direction: single. */
    @SerialName(value = "filters") val filters: kotlin.collections.List<TicketProductPropertyFilter>? = null

)
