/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param routeId Route identification for internal logging, from routes response
 * @param routeSegments All route segments
 */
@Serializable
data class GetTicketProductOffersByRouteRequest(

    /* Route identification for internal logging, from routes response */
    @SerialName(value = "routeId") @Required val routeId: kotlin.String,

    /* All route segments */
    @SerialName(value = "routeSegments") @Required val routeSegments: kotlin.collections.List<TicketsRouteSegment>

)
