/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Happiness configuration for a user
 *
 * @param eventRepeatTimes Defines event count for HappinessFeedback appearance
 * @param monthlyRepeatTimes Defines how often happiness feedback will appear per month
 * @param excludedProvidersIds Defines providers that won't trigger feedback request
 */
@Serializable
data class HappinessFeedbackConfigResponse(

    /* Defines event count for HappinessFeedback appearance */
    @SerialName(value = "eventRepeatTimes") @Required val eventRepeatTimes: kotlin.Int,

    /* Defines how often happiness feedback will appear per month */
    @SerialName(value = "monthlyRepeatTimes") @Required val monthlyRepeatTimes: kotlin.Int,

    /* Defines providers that won't trigger feedback request */
    @SerialName(value = "excludedProvidersIds") @Required val excludedProvidersIds: kotlin.collections.List<kotlin.String>

)
