/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param price
 * @param priceBreakdowns
 * @param invoiceUrls
 * @param isInvoiceAvailable
 * @param purchaseBreakdown
 * @param method
 * @param tripPurpose
 */
@Serializable
data class HistoryPayment(

    @SerialName(value = "price") @Required val price: kotlin.String,

    @SerialName(value = "priceBreakdowns") @Required val priceBreakdowns: kotlin.collections.List<PriceBreakdown>,

    @SerialName(value = "invoiceUrls") @Required val invoiceUrls: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "isInvoiceAvailable") @Required val isInvoiceAvailable: kotlin.Boolean,

    @SerialName(value = "purchaseBreakdown") val purchaseBreakdown: PurchaseBreakdown? = null,

    @SerialName(value = "method") val method: PaymentMethod? = null,

    @SerialName(value = "tripPurpose") val tripPurpose: TripPurpose? = null

)
