/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param title
 * @param providerId
 * @param providerName
 * @param date
 * @param payment
 * @param properties
 * @param supportContacts
 * @param status
 * @param providerColor
 * @param providerAccentColor
 * @param providerIcon
 * @param faq
 * @param supportInfo
 * @param shoppingCartId
 * @param departureStopName
 */
@Serializable
data class HistoryTicketItem(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "providerId") @Required val providerId: kotlin.String,

    @SerialName(value = "providerName") @Required val providerName: kotlin.String,

    @SerialName(value = "date") @Required val date: kotlin.String,

    @SerialName(value = "payment") @Required val payment: HistoryPayment,

    @SerialName(value = "properties") @Required val properties: kotlin.collections.List<TicketProductProperty>,

    @SerialName(value = "supportContacts") @Required val supportContacts: kotlin.collections.List<SupportContact>,

    @SerialName(value = "status") @Required val status: HistoryTicketItemStatus,

    @SerialName(value = "providerColor") val providerColor: kotlin.String? = null,

    @SerialName(value = "providerAccentColor") val providerAccentColor: kotlin.String? = null,

    @SerialName(value = "providerIcon") val providerIcon: kotlin.String? = null,

    @SerialName(value = "faq") val faq: Faq? = null,

    @SerialName(value = "supportInfo") val supportInfo: SupportInfo? = null,

    @SerialName(value = "shoppingCartId") val shoppingCartId: kotlin.String? = null,

    @SerialName(value = "departureStopName") val departureStopName: kotlin.String? = null

)
