/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param title
 * @param providerId
 * @param providerName
 * @param date
 * @param providerColor
 * @param providerAccentColor
 * @param providerIcon
 * @param start
 * @param end
 * @param faq
 * @param supportInfo
 * @param brandAndModel
 * @param plateNumber
 * @param shape
 * @param totalTripTimeSeconds
 * @param notes
 * @param payment
 */
@Serializable
data class HistoryVehicleSharingItem(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "providerId") @Required val providerId: kotlin.String,

    @SerialName(value = "providerName") @Required val providerName: kotlin.String,

    @SerialName(value = "date") @Required val date: kotlin.String,

    @SerialName(value = "providerColor") val providerColor: kotlin.String? = null,

    @SerialName(value = "providerAccentColor") val providerAccentColor: kotlin.String? = null,

    @SerialName(value = "providerIcon") val providerIcon: kotlin.String? = null,

    @SerialName(value = "start") val start: Location? = null,

    @SerialName(value = "end") val end: Location? = null,

    @SerialName(value = "faq") val faq: Faq? = null,

    @SerialName(value = "supportInfo") val supportInfo: SupportInfo? = null,

    @SerialName(value = "brandAndModel") val brandAndModel: kotlin.String? = null,

    @SerialName(value = "plateNumber") val plateNumber: kotlin.String? = null,

    @SerialName(value = "shape") val shape: kotlin.String? = null,

    @SerialName(value = "totalTripTimeSeconds") val totalTripTimeSeconds: kotlin.Long? = null,

    @SerialName(value = "notes") val notes: kotlin.collections.List<Note>? = null,

    @SerialName(value = "payment") val payment: HistoryPayment? = null

)
