/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param rideHailing
 * @param vehicleSharing
 * @param ticket
 * @param ticketActivation
 * @param subscription
 * @param rental
 */
@Serializable
data class HistoryItem(

    @SerialName(value = "rideHailing") val rideHailing: HistoryRideHailingItem? = null,

    @SerialName(value = "vehicleSharing") val vehicleSharing: HistoryVehicleSharingItem? = null,

    @SerialName(value = "ticket") val ticket: HistoryTicketItem? = null,

    @SerialName(value = "ticketActivation") val ticketActivation: HistoryTicketActivationItem? = null,

    @SerialName(value = "subscription") val subscription: HistorySubscriptionItem? = null,

    @SerialName(value = "rental") val rental: HistoryRentalItem? = null

)
