/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param type
 * @param name
 * @param icon
 * @param color
 * @param transports Actually unused
 * @param filterItems
 * @param providerIds
 * @param groupTransports True if underlying transports should be wrapped under a single item
 * @param sharingVehicleType
 * @param accentColor
 * @param comingSoonInfo
 */
@Serializable
data class HomeItem(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "type") @Required val type: HomeItemType,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "icon") @Required val icon: kotlin.String,

    @SerialName(value = "color") @Required val color: kotlin.String,

    /* Actually unused */
    @SerialName(value = "transports") @Required val transports: kotlin.collections.List<Transport>,

    @SerialName(value = "filterItems") @Required val filterItems: kotlin.collections.List<FilterItem>,

    @SerialName(value = "providerIds") @Required val providerIds: kotlin.collections.List<kotlin.String>,

    /* True if underlying transports should be wrapped under a single item */
    @SerialName(value = "groupTransports") @Required val groupTransports: kotlin.Boolean,

    @SerialName(value = "sharingVehicleType") val sharingVehicleType: VehicleType? = null,

    @SerialName(value = "accentColor") val accentColor: kotlin.String? = null,

    @SerialName(value = "comingSoonInfo") val comingSoonInfo: ComingSoonInfo? = null

)
