/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param howToStartBookingWebUrl
 * @param howToEndBookingWebUrl
 * @param howToInstantStartBookingWebUrl
 */
@Serializable
data class HowItWorks(

    @SerialName(value = "howToStartBookingWebUrl") @Required val howToStartBookingWebUrl: kotlin.String,

    @SerialName(value = "howToEndBookingWebUrl") @Required val howToEndBookingWebUrl: kotlin.String,

    @SerialName(value = "howToInstantStartBookingWebUrl") val howToInstantStartBookingWebUrl: kotlin.String? = null

)
