/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param status
 * @param unfulfilledReason
 * @param title
 * @param subtitle
 * @param buttonText
 */
@Serializable
data class IdentityRequirement(

    @SerialName(value = "status") @Required val status: IdentityRequirementStatus,

    @SerialName(value = "unfulfilledReason") val unfulfilledReason: kotlin.String? = null,

    @SerialName(value = "title") val title: kotlin.String? = null,

    @SerialName(value = "subtitle") val subtitle: kotlin.String? = null,

    @SerialName(value = "buttonText") val buttonText: kotlin.String? = null

)
