/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param verificationStatus
 * @param verificationMessageKey
 * @param verificationFallbackMessage
 */
@Serializable
data class Identity(

    @SerialName(value = "verificationStatus") @Required val verificationStatus: VerificationStatus,

    @SerialName(value = "verificationMessageKey") val verificationMessageKey: kotlin.String? = null,

    @SerialName(value = "verificationFallbackMessage") val verificationFallbackMessage: kotlin.String? = null

)
