/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param scannerScreenTitle
 * @param scannerScreenNoPermissionText
 * @param openManualNumberInputButtonTitle
 * @param manualNumberScreenTitle
 * @param manualNumberInputLabelText
 * @param manualNumberInputWhereToFindText
 * @param manualNumberInputConfirmIdButtonTitle
 */
@Serializable
data class InstantUnlockData(

    @SerialName(value = "scannerScreenTitle") @Required val scannerScreenTitle: kotlin.String,

    @SerialName(value = "scannerScreenNoPermissionText") @Required val scannerScreenNoPermissionText: kotlin.String,

    @SerialName(value = "openManualNumberInputButtonTitle") @Required val openManualNumberInputButtonTitle: kotlin.String,

    @SerialName(value = "manualNumberScreenTitle") @Required val manualNumberScreenTitle: kotlin.String,

    @SerialName(value = "manualNumberInputLabelText") @Required val manualNumberInputLabelText: kotlin.String,

    @SerialName(value = "manualNumberInputWhereToFindText") @Required val manualNumberInputWhereToFindText: kotlin.String,

    @SerialName(value = "manualNumberInputConfirmIdButtonTitle") @Required val manualNumberInputConfirmIdButtonTitle: kotlin.String

)
