/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param fromSecondsAfterMidnight
 * @param toSecondsAfterMidnight
 * @param frequencySeconds
 * @param tags
 * @param tripId
 * @param destination
 * @param timeLabel
 * @param platformName
 */
@Serializable
data class IntervalTime(

    @SerialName(value = "fromSecondsAfterMidnight") @Required val fromSecondsAfterMidnight: kotlin.Int,

    @SerialName(value = "toSecondsAfterMidnight") @Required val toSecondsAfterMidnight: kotlin.Int,

    @SerialName(value = "frequencySeconds") @Required val frequencySeconds: kotlin.Int,

    @SerialName(value = "tags") @Required val tags: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "tripId") val tripId: kotlin.String? = null,

    @SerialName(value = "destination") val destination: kotlin.String? = null,

    @SerialName(value = "timeLabel") val timeLabel: kotlin.String? = null,

    @SerialName(value = "platformName") val platformName: kotlin.String? = null

)
