/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*

/**
 *
 *
 * Values: LOCATION_TYPE_NONE,STOPS,POI,ADDRESS,COORDINATE,CURRENT_LOCATION
 */
@Serializable
enum class LocationType(val value: kotlin.String) {

    @SerialName(value = "LOCATION_TYPE_NONE")
    LOCATION_TYPE_NONE("LOCATION_TYPE_NONE"),

    @SerialName(value = "STOPS")
    STOPS("STOPS"),

    @SerialName(value = "POI")
    POI("POI"),

    @SerialName(value = "ADDRESS")
    ADDRESS("ADDRESS"),

    @SerialName(value = "COORDINATE")
    COORDINATE("COORDINATE"),

    @SerialName(value = "CURRENT_LOCATION")
    CURRENT_LOCATION("CURRENT_LOCATION");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is LocationType) "$data" else null

        /**
         * Returns a valid [LocationType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): LocationType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
