/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param image
 * @param heading
 * @param label
 * @param paragraph
 * @param pictograph
 */
@Serializable
data class ManualItem(

    @SerialName(value = "image") val image: ManualImage? = null,

    @SerialName(value = "heading") val heading: ManualText? = null,

    @SerialName(value = "label") val label: ManualText? = null,

    @SerialName(value = "paragraph") val paragraph: ManualParagraph? = null,

    @SerialName(value = "pictograph") val pictograph: ManualPictograph? = null

)
