/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param stops
 * @param sharedVehicles
 * @param sharedGroups
 * @param transitVehicles
 */
@Serializable
data class MapObjectsResponse(

    @SerialName(value = "stops") @Required val stops: kotlin.collections.List<StopWithSchedules>,

    @SerialName(value = "sharedVehicles") @Required val sharedVehicles: kotlin.collections.List<ProviderWithVehicles>,

    @SerialName(value = "sharedGroups") @Required val sharedGroups: kotlin.collections.List<ProviderWithGroups>,

    @SerialName(value = "transitVehicles") @Required val transitVehicles: kotlin.collections.List<TransitVehiclePositionWithScheduleAndTrack>

)
