/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param status
 * @param type
 * @param faq
 */
@Serializable
data class MembershipRequirement(

    @SerialName(value = "status") @Required val status: MembershipRequirementStatus,

    @SerialName(value = "type") @Required val type: MembershipType,

    @SerialName(value = "faq") val faq: Faq? = null

)
