/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param paymentTitle
 * @param paymentSubtitle
 * @param balance
 * @param allowance
 * @param currency
 * @param companyId
 * @param employeeId
 * @param paymentDetails
 * @param cycle
 * @param allowanceBreakdown
 * @param budgetId
 * @param cards
 * @param trial
 * @param resetCycle
 * @param resetDate
 * @param renewalDate
 */
@Serializable
data class MobilityBudget(

    @SerialName(value = "paymentTitle") @Required val paymentTitle: kotlin.String,

    @SerialName(value = "paymentSubtitle") @Required val paymentSubtitle: kotlin.String,

    @SerialName(value = "balance") @Required val balance: kotlin.Double,

    @SerialName(value = "allowance") @Required val allowance: kotlin.Double,

    @SerialName(value = "currency") @Required val currency: kotlin.String,

    @SerialName(value = "companyId") @Required val companyId: kotlin.String,

    @SerialName(value = "employeeId") @Required val employeeId: kotlin.String,

    @SerialName(value = "paymentDetails") @Required val paymentDetails: kotlin.collections.List<PaymentDetail>,

    @SerialName(value = "cycle") @Required val cycle: BudgetCycle,

    @SerialName(value = "allowanceBreakdown") @Required val allowanceBreakdown: kotlin.collections.List<AllowanceBreakdownItem>,

    @SerialName(value = "budgetId") @Required val budgetId: kotlin.String,

    @SerialName(value = "cards") @Required val cards: kotlin.collections.List<PaymentCard>,

    @SerialName(value = "trial") val trial: MobilityBudgetTrial? = null,

    @SerialName(value = "resetCycle") val resetCycle: ResetCycle? = null,

    @SerialName(value = "resetDate") val resetDate: kotlin.String? = null,

    @SerialName(value = "renewalDate") val renewalDate: kotlin.String? = null

)
