/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param firstName
 * @param email
 * @param companyName
 * @param lastName
 * @param budget
 */
@Serializable
data class MobilityBudgetsInvitationResponse(

    @SerialName(value = "firstName") @Required val firstName: kotlin.String,

    @SerialName(value = "email") @Required val email: kotlin.String,

    @SerialName(value = "companyName") @Required val companyName: kotlin.String,

    @SerialName(value = "lastName") val lastName: kotlin.String? = null,

    @SerialName(value = "budget") val budget: Budget? = null

)
