/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param budgetId
 * @param allowance
 * @param currency
 * @param allowanceBreakdown
 * @param cycle
 * @param howItWorks
 * @param trial
 * @param renewalDate
 * @param resetCycle
 * @param resetDate
 * @param helpUrl
 */
@Serializable
data class MobilityBudgetOverviewResponse(

    @SerialName(value = "budgetId") @Required val budgetId: kotlin.String,

    @SerialName(value = "allowance") @Required val allowance: kotlin.Double,

    @SerialName(value = "currency") @Required val currency: kotlin.String,

    @SerialName(value = "allowanceBreakdown") @Required val allowanceBreakdown: BudgetAllowanceBreakdown,

    @SerialName(value = "cycle") @Required val cycle: BudgetCycle,

    @SerialName(value = "howItWorks") @Required val howItWorks: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "trial") val trial: MobilityBudgetTrial? = null,

    @SerialName(value = "renewalDate") val renewalDate: kotlin.String? = null,

    @SerialName(value = "resetCycle") val resetCycle: ResetCycle? = null,

    @SerialName(value = "resetDate") val resetDate: kotlin.String? = null,

    @SerialName(value = "helpUrl") val helpUrl: kotlin.String? = null

)
