/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param amount
 * @param currency ISO 4217 currency code, e.g. \"EUR\"
 * @param text Formatted text representation
 */
@Serializable
data class Money(

    @SerialName(value = "amount") @Required val amount: kotlin.Double,

    /* ISO 4217 currency code, e.g. \"EUR\" */
    @SerialName(value = "currency") @Required val currency: kotlin.String,

    /* Formatted text representation */
    @SerialName(value = "text") val text: kotlin.String? = null

)
