/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param displayType
 * @param onClick
 * @param banner
 * @param fullScreen
 * @param deepLink
 * @param webUrl
 */
@Serializable
data class Notification(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "displayType") @Required val displayType: NotificationDisplayType,

    @SerialName(value = "onClick") @Required val onClick: NotificationOnClickAction,

    @SerialName(value = "banner") val banner: NotificationBanner? = null,

    @SerialName(value = "fullScreen") val fullScreen: NotificationFullScreen? = null,

    @SerialName(value = "deepLink") val deepLink: kotlin.String? = null,

    @SerialName(value = "webUrl") val webUrl: kotlin.String? = null

)
