/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * NPS configuration for a user
 *
 * @param requestNps If true, app should request NPS from user, NOW.
 * @param npsCanBeShown If this is false, NPS should not be shown under any circumstances.
 * @param npsPromptIntervalDays If not null, app should use this period for nps.
 * @param npsFirstPromptIntervalDays If not null, app should use this period for first nps display.
 */
@Serializable
data class NpsFeedbackConfigResponse(

    /* If true, app should request NPS from user, NOW. */
    @SerialName(value = "requestNps") @Required val requestNps: kotlin.Boolean,

    /* If this is false, NPS should not be shown under any circumstances. */
    @SerialName(value = "npsCanBeShown") @Required val npsCanBeShown: kotlin.Boolean,

    /* If not null, app should use this period for nps. */
    @SerialName(value = "npsPromptIntervalDays") val npsPromptIntervalDays: kotlin.Long? = null,

    /* If not null, app should use this period for first nps display. */
    @SerialName(value = "npsFirstPromptIntervalDays") val npsFirstPromptIntervalDays: kotlin.Long? = null

)
