/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param isOperating
 * @param zones
 * @param restrictionsInfoMessage
 * @param notOperatingReason
 */
@Serializable
data class OperationRestrictions(

    @SerialName(value = "isOperating") @Required val isOperating: kotlin.Boolean,

    @SerialName(value = "zones") @Required val zones: kotlin.collections.List<Zone>,

    @SerialName(value = "restrictionsInfoMessage") @Required val restrictionsInfoMessage: kotlin.String,

    @SerialName(value = "notOperatingReason") @Required val notOperatingReason: kotlin.String

)
