/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param phoneNumber
 * @param method
 * @param length
 * @param type
 */
@Serializable
data class OTPPhoneChallenge(

    @SerialName(value = "phoneNumber") val phoneNumber: kotlin.String? = null,

    @SerialName(value = "method") val method: kotlin.String? = null,

    @SerialName(value = "length") val length: kotlin.Int? = null,

    @SerialName(value = "type") val type: kotlin.String? = null

)
