/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param type
 * @param isDefault
 * @param shouldRefreshAfterPurchase
 * @param canNotBeDeleted
 * @param tripPurposes
 * @param creditCard
 * @param directDebit
 * @param paypal
 * @param prePay
 * @param digitalWallet
 * @param mobilityBudget
 */
@Serializable
data class PaymentMethod(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "type") @Required val type: PaymentMethodType,

    @SerialName(value = "isDefault") @Required val isDefault: kotlin.Boolean,

    @SerialName(value = "shouldRefreshAfterPurchase") @Required val shouldRefreshAfterPurchase: kotlin.Boolean,

    @SerialName(value = "canNotBeDeleted") @Required val canNotBeDeleted: kotlin.Boolean,

    @SerialName(value = "tripPurposes") @Required val tripPurposes: kotlin.collections.List<TripPurpose>,

    @SerialName(value = "creditCard") val creditCard: CreditCardInfo? = null,

    @SerialName(value = "directDebit") val directDebit: DirectDebitInfo? = null,

    @SerialName(value = "paypal") val paypal: Paypal? = null,

    @SerialName(value = "prePay") val prePay: PrePay? = null,

    @SerialName(value = "digitalWallet") val digitalWallet: DigitalWalletInfo? = null,

    @SerialName(value = "mobilityBudget") val mobilityBudget: MobilityBudget? = null

)
