/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param name
 * @param supportedPaymentMethods
 * @param supportEmail
 * @param supportInfo
 * @param faq
 * @param paymentMethodsSubtitle
 * @param displayContacts
 * @param references
 */
@Serializable
data class PaymentsProvider(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "supportedPaymentMethods") @Required val supportedPaymentMethods: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "supportEmail") val supportEmail: kotlin.String? = null,

    @SerialName(value = "supportInfo") val supportInfo: SupportInfo? = null,

    @SerialName(value = "faq") val faq: Faq? = null,

    @SerialName(value = "paymentMethodsSubtitle") val paymentMethodsSubtitle: kotlin.String? = null,

    @SerialName(value = "displayContacts") val displayContacts: kotlin.Boolean? = null,

    @SerialName(value = "references") val references: kotlin.collections.List<Reference>? = null

)
