/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param status
 * @param lastNumbers
 * @param expirationDate
 */
@Serializable
data class PaymentCard(

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "status") val status: CardStatus? = null,

    @SerialName(value = "lastNumbers") val lastNumbers: kotlin.String? = null,

    @SerialName(value = "expirationDate") val expirationDate: kotlin.String? = null

)
