/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param paymentId
 * @param amount
 * @param currency
 */
@Serializable
data class PaymentConfirmation(

    @SerialName(value = "paymentId") val paymentId: kotlin.String? = null,

    @SerialName(value = "amount") val amount: kotlin.Double? = null,

    @SerialName(value = "currency") val currency: kotlin.String? = null

)
