/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param southLat
 * @param northLat
 * @param westLng
 * @param eastLng
 */
@Serializable
data class PlatformLatLngBounds(

    @SerialName(value = "southLat") @Required val southLat: kotlin.Double,

    @SerialName(value = "northLat") @Required val northLat: kotlin.Double,

    @SerialName(value = "westLng") @Required val westLng: kotlin.Double,

    @SerialName(value = "eastLng") @Required val eastLng: kotlin.Double

)
