/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param providerId
 * @param bookingId
 * @param rating
 * @param needsSupport
 * @param categories
 * @param comment
 * @param groupType
 */
@Serializable
data class PostRideFeedbackSubmitRequest(

    @SerialName(value = "providerId") @Required val providerId: kotlin.String,

    @SerialName(value = "bookingId") @Required val bookingId: kotlin.String,

    @SerialName(value = "rating") @Required val rating: HappinessFeedbackRating,

    @SerialName(value = "needsSupport") @Required val needsSupport: kotlin.Boolean,

    @SerialName(value = "categories") val categories: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "comment") val comment: kotlin.String? = null,

    @SerialName(value = "groupType") val groupType: ProviderGroupType? = null

)
