/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param paymentTitle
 * @param paymentSubtitle
 * @param paymentDetails
 * @param balance
 */
@Serializable
data class PrePay(

    @SerialName(value = "paymentTitle") @Required val paymentTitle: kotlin.String,

    @SerialName(value = "paymentSubtitle") @Required val paymentSubtitle: kotlin.String,

    @SerialName(value = "paymentDetails") @Required val paymentDetails: kotlin.collections.List<PaymentDetail>,

    @SerialName(value = "balance") @Required val balance: kotlin.Double

)
