/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param name
 * @param id
 * @param providerId
 * @param serviceLocations
 * @param codeUsageInstructions
 */
@Serializable
data class ProductInfo(

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "providerId") @Required val providerId: kotlin.String,

    @SerialName(value = "serviceLocations") @Required val serviceLocations: kotlin.collections.List<ServiceLocation>,

    @SerialName(value = "codeUsageInstructions") val codeUsageInstructions: kotlin.String? = null

)
