/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import com.trafi.core.model.Gender

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param gender 
 * @param firstName 
 * @param lastName 
 * @param displayName 
 * @param email 
 * @param addressLineOne 
 * @param addressLineTwo 
 * @param city 
 * @param country 
 * @param birthDate 
 * @param ageRange 
 * @param postCode 
 */
@Serializable
data class Profile (

    @SerialName(value = "gender") @Required val gender: Gender,

    @SerialName(value = "firstName") val firstName: kotlin.String? = null,

    @SerialName(value = "lastName") val lastName: kotlin.String? = null,

    @SerialName(value = "displayName") val displayName: kotlin.String? = null,

    @SerialName(value = "email") val email: kotlin.String? = null,

    @SerialName(value = "addressLineOne") val addressLineOne: kotlin.String? = null,

    @SerialName(value = "addressLineTwo") val addressLineTwo: kotlin.String? = null,

    @SerialName(value = "city") val city: kotlin.String? = null,

    @SerialName(value = "country") val country: kotlin.String? = null,

    @SerialName(value = "birthDate") val birthDate: kotlin.String? = null,

    @SerialName(value = "ageRange") val ageRange: kotlin.String? = null,

    @SerialName(value = "postCode") val postCode: kotlin.String? = null

)

