/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param registrationDeepLinkIos
 * @param registrationDeepLinkAndroid
 * @param connectionDeepLinkIos
 * @param connectionDeepLinkAndroid
 * @param connectionWebFormUrlAndroid
 * @param connectionWebFormUrlIos
 */
@Serializable
data class ProviderConnectionParameters(

    @SerialName(value = "registrationDeepLinkIos") val registrationDeepLinkIos: DeepLinkIos? = null,

    @SerialName(value = "registrationDeepLinkAndroid") val registrationDeepLinkAndroid: DeepLinkAndroid? = null,

    @SerialName(value = "connectionDeepLinkIos") val connectionDeepLinkIos: DeepLinkIos? = null,

    @SerialName(value = "connectionDeepLinkAndroid") val connectionDeepLinkAndroid: DeepLinkAndroid? = null,

    @SerialName(value = "connectionWebFormUrlAndroid") val connectionWebFormUrlAndroid: kotlin.String? = null,

    @SerialName(value = "connectionWebFormUrlIos") val connectionWebFormUrlIos: kotlin.String? = null

)
