/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param title
 * @param providerId
 * @param sections
 * @param vehicleType
 * @param vehicleSubtype
 * @param providerGroupType
 * @param instantUnlock
 * @param howToStart
 * @param howToEnd
 * @param onboarding
 */
@Serializable
data class ProviderManualSections(

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "providerId") @Required val providerId: kotlin.String,

    @SerialName(value = "sections") @Required val sections: kotlin.collections.List<ManualSection>,

    @SerialName(value = "vehicleType") val vehicleType: VehicleType? = null,

    @SerialName(value = "vehicleSubtype") val vehicleSubtype: kotlin.String? = null,

    @SerialName(value = "providerGroupType") val providerGroupType: ProviderGroupType? = null,

    @SerialName(value = "instantUnlock") val instantUnlock: ManualSection? = null,

    @SerialName(value = "howToStart") val howToStart: ManualSection? = null,

    @SerialName(value = "howToEnd") val howToEnd: ManualSection? = null,

    @SerialName(value = "onboarding") val onboarding: ManualSection? = null

)
