/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param name
 * @param type
 * @param providersWithRequirements
 * @param sharingVehicleType
 */
@Serializable
data class ProviderWithRequirementsGroup(

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "type") @Required val type: ProviderGroupType,

    @SerialName(value = "providersWithRequirements") @Required val providersWithRequirements: kotlin.collections.List<ProviderWithRequirements>,

    @SerialName(value = "sharingVehicleType") val sharingVehicleType: VehicleType? = null

)
