/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param provider
 * @param vehicles
 * @param vehicleGroups
 * @param instantUnlockEnabled
 */
@Serializable
data class ProviderWithVehiclesAndGroups(

    @SerialName(value = "provider") @Required val provider: Provider,

    @SerialName(value = "vehicles") @Required val vehicles: kotlin.collections.List<VehicleWithWalkDuration>,

    @SerialName(value = "vehicleGroups") @Required val vehicleGroups: kotlin.collections.List<VehicleGroup>,

    @SerialName(value = "instantUnlockEnabled") @Required val instantUnlockEnabled: kotlin.Boolean

)
