/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param supportsConnect
 * @param supportsRegistration
 * @param requiresPayment
 * @param connectionNotes
 * @param connectionLocalizations
 */
@Serializable
data class ProviderFeatures(

    @SerialName(value = "supportsConnect") @Required val supportsConnect: kotlin.Boolean,

    @SerialName(value = "supportsRegistration") @Required val supportsRegistration: kotlin.Boolean,

    @SerialName(value = "requiresPayment") @Required val requiresPayment: kotlin.Boolean,

    @SerialName(value = "connectionNotes") @Required val connectionNotes: kotlin.String,

    @SerialName(value = "connectionLocalizations") val connectionLocalizations: ConnectionLocalizations? = null

)
