/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param prefix
 * @param suffix
 * @param tags
 */
@Serializable
data class PurchaseBreakdownItem(

    @SerialName(value = "prefix") @Required val prefix: kotlin.String,

    @SerialName(value = "suffix") @Required val suffix: kotlin.String,

    @SerialName(value = "tags") val tags: kotlin.collections.List<kotlin.String>? = null

)
