/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param total
 * @param purchaseBreakdownItems
 * @param original
 * @param suffix
 */
@Serializable
data class PurchaseBreakdown(

    @SerialName(value = "total") @Required val total: kotlin.String,

    @SerialName(value = "purchaseBreakdownItems") @Required val purchaseBreakdownItems: kotlin.collections.List<PurchaseBreakdownItem>,

    @SerialName(value = "original") val original: kotlin.String? = null,

    @SerialName(value = "suffix") val suffix: kotlin.String? = null

)
