/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param name
 * @param countryId
 * @param countryName
 * @param timeZone
 * @param coordinates
 * @param homeItems
 * @param supportContacts
 * @param routeSearchConfig
 * @param ticketProviderId
 */
@Serializable
data class Region(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "countryId") @Required val countryId: kotlin.String,

    @SerialName(value = "countryName") @Required val countryName: kotlin.String,

    @SerialName(value = "timeZone") @Required val timeZone: kotlin.String,

    @SerialName(value = "coordinates") @Required val coordinates: RegionCoordinates,

    @SerialName(value = "homeItems") @Required val homeItems: kotlin.collections.List<HomeItem>,

    @SerialName(value = "supportContacts") @Required val supportContacts: kotlin.collections.List<SupportContact>,

    @SerialName(value = "routeSearchConfig") @Required val routeSearchConfig: RouteSearchConfig,

    @SerialName(value = "ticketProviderId") val ticketProviderId: kotlin.String? = null

)
