/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import com.trafi.core.model.RentalStation
import com.trafi.core.model.StationAvailability
import com.trafi.core.model.WalkPath

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param station 
 * @param availabilities 
 * @param path 
 */
@Serializable
data class RentalStationWithAvailabilities (

    @SerialName(value = "station") @Required val station: RentalStation,

    @SerialName(value = "availabilities") @Required val availabilities: kotlin.collections.List<StationAvailability>,

    @SerialName(value = "path") val path: WalkPath? = null

)

