/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param mode
 * @param fromStationId
 * @param filters
 * @param toStationId
 * @param startTime
 * @param endTime
 */
@Serializable
data class RentalBookingTrip(

    @SerialName(value = "mode") @Required val mode: RentalTripMode,

    @SerialName(value = "fromStationId") @Required val fromStationId: kotlin.String,

    @SerialName(value = "filters") @Required val filters: kotlin.collections.List<FilterSelection>,

    @SerialName(value = "toStationId") val toStationId: kotlin.String? = null,

    @SerialName(value = "startTime") val startTime: kotlin.String? = null,

    @SerialName(value = "endTime") val endTime: kotlin.String? = null

)
