/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param earliestLeaseTime some providers allow leasing the booking earlier than the start time
 * @param latestLeaseTime some providers expect the booking to be leased no later than certain time after the start time
 */
@Serializable
data class RentalBookingRestrictions(

    /* some providers allow leasing the booking earlier than the start time */
    @SerialName(value = "earliestLeaseTime") val earliestLeaseTime: kotlin.String? = null,

    /* some providers expect the booking to be leased no later than certain time after the start time */
    @SerialName(value = "latestLeaseTime") val latestLeaseTime: kotlin.String? = null

)
