/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param providerId
 * @param type
 * @param imageUrls
 * @param tags
 * @param sustainability
 * @param isNew
 * @param colors
 * @param technicalData
 * @param configuration
 * @param subtype
 * @param stationId
 * @param name
 * @param categoryName
 * @param isFinal
 * @param location
 * @param licencePlate
 * @param pricing
 * @param imageUrl
 * @param battery
 * @param fuel
 * @param rangeRemaining
 * @param description
 * @param availableFrom
 */
@Serializable
data class RentalVehicle(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "providerId") @Required val providerId: kotlin.String,

    @SerialName(value = "type") @Required val type: VehicleType,

    @SerialName(value = "imageUrls") @Required val imageUrls: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "tags") @Required val tags: kotlin.collections.List<Tag>,

    @SerialName(value = "sustainability") @Required val sustainability: SustainabilityProperties,

    @SerialName(value = "isNew") @Required val isNew: kotlin.Boolean,

    @SerialName(value = "colors") @Required val colors: kotlin.collections.List<Color>,

    @SerialName(value = "technicalData") @Required val technicalData: TechnicalData,

    @SerialName(value = "configuration") @Required val configuration: kotlin.collections.List<Configuration>,

    @SerialName(value = "subtype") val subtype: kotlin.String? = null,

    @SerialName(value = "stationId") val stationId: kotlin.String? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "categoryName") val categoryName: kotlin.String? = null,

    @SerialName(value = "isFinal") val isFinal: kotlin.Boolean? = null,

    @SerialName(value = "location") val location: Location? = null,

    @SerialName(value = "licencePlate") val licencePlate: kotlin.String? = null,

    @SerialName(value = "pricing") val pricing: VehiclePricing? = null,

    @SerialName(value = "imageUrl") val imageUrl: kotlin.String? = null,

    @SerialName(value = "battery") val battery: Battery? = null,

    @SerialName(value = "fuel") val fuel: Fuel? = null,

    @SerialName(value = "rangeRemaining") val rangeRemaining: kotlin.Int? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "availableFrom") val availableFrom: kotlin.String? = null

)
