/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param northEast
 * @param southWest
 * @param providerIds Comma separated list.
 * @param vehicleType
 * @param mode
 * @param startTime ISO 8601 date and time, including the offset from UTC, e.g. \"2018-06-14T10:15:00+02:00\".
 * @param endTime
 * @param fromStationId
 */
@Serializable
data class RentalMapRequest(

    @SerialName(value = "northEast") @Required val northEast: LatLng,

    @SerialName(value = "southWest") @Required val southWest: LatLng,

    /* Comma separated list. */
    @SerialName(value = "providerIds") @Required val providerIds: kotlin.String,

    @SerialName(value = "vehicleType") @Required val vehicleType: VehicleType,

    @SerialName(value = "mode") @Required val mode: RentalTripMode,

    /* ISO 8601 date and time, including the offset from UTC, e.g. \"2018-06-14T10:15:00+02:00\". */
    @SerialName(value = "startTime") @Required val startTime: kotlin.String,

    @SerialName(value = "endTime") @Required val endTime: kotlin.String,

    @SerialName(value = "fromStationId") val fromStationId: kotlin.String? = null

)
