/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param vehicle
 * @param priceBreakdown
 * @param availableFrom
 * @param filters
 * @param additionalServices
 * @param delivery
 * @param benefits
 */
@Serializable
data class RentalVehicleOffer(

    @SerialName(value = "vehicle") @Required val vehicle: RentalVehicle,

    @SerialName(value = "priceBreakdown") @Required val priceBreakdown: VehicleOfferBreakdown,

    @SerialName(value = "availableFrom") val availableFrom: kotlin.String? = null,

    @SerialName(value = "filters") val filters: FilterGroup? = null,

    @SerialName(value = "additionalServices") val additionalServices: Filter? = null,

    @SerialName(value = "delivery") val delivery: Filter? = null,

    @SerialName(value = "benefits") val benefits: Benefits? = null

)
