/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param mode
 * @param vehicleType
 * @param transportIcon
 * @param booking
 * @param vehicleSubtype
 * @param filters
 */
@Serializable
data class RentalProviderOptions(

    @SerialName(value = "mode") @Required val mode: RentalTripMode,

    @SerialName(value = "vehicleType") @Required val vehicleType: VehicleType,

    @SerialName(value = "transportIcon") @Required val transportIcon: kotlin.String,

    @SerialName(value = "booking") @Required val booking: RentalBookingOptions,

    @SerialName(value = "vehicleSubtype") val vehicleSubtype: kotlin.String? = null,

    @SerialName(value = "filters") val filters: kotlin.collections.List<Filter>? = null

)
