/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param providerId
 * @param location
 * @param stationOperator
 * @param imageUrls
 * @param vehicleType
 * @param name
 * @param description
 */
@Serializable
data class RentalStation(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "providerId") @Required val providerId: kotlin.String,

    @SerialName(value = "location") @Required val location: Location,

    @SerialName(value = "stationOperator") @Required val stationOperator: StationOperator,

    @SerialName(value = "imageUrls") @Required val imageUrls: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "vehicleType") val vehicleType: VehicleType? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null

)
