/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param type
 * @param fulfilled
 * @param personalDetails
 * @param addressDetails
 * @param drivingLicence
 * @param identity
 * @param phoneNumber
 * @param paymentMethod
 * @param term
 * @param membership
 */
@Serializable
data class Requirement(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "type") @Required val type: RequirementType,

    @SerialName(value = "fulfilled") @Required val fulfilled: kotlin.Boolean,

    @SerialName(value = "personalDetails") val personalDetails: PersonalDetailsRequirement? = null,

    @SerialName(value = "addressDetails") val addressDetails: AddressDetailsRequirement? = null,

    @SerialName(value = "drivingLicence") val drivingLicence: DrivingLicenceRequirement? = null,

    @SerialName(value = "identity") val identity: IdentityRequirement? = null,

    @SerialName(value = "phoneNumber") val phoneNumber: PhoneNumberRequirement? = null,

    @SerialName(value = "paymentMethod") val paymentMethod: PaymentMethodRequirement? = null,

    @SerialName(value = "term") val term: TermRequirement? = null,

    @SerialName(value = "membership") val membership: MembershipRequirement? = null

)
