/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param providerId
 * @param displayName
 * @param isSharedRide
 * @param description
 * @param seatCount
 * @param pricingTitle
 * @param pricingDetails
 * @param pricingDescription
 * @param howItWorks
 * @param operationRestrictions
 */
@Serializable
data class RideHailingProduct(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "providerId") @Required val providerId: kotlin.String,

    @SerialName(value = "displayName") @Required val displayName: kotlin.String,

    @SerialName(value = "isSharedRide") @Required val isSharedRide: kotlin.Boolean,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "seatCount") val seatCount: kotlin.Int? = null,

    @SerialName(value = "pricingTitle") val pricingTitle: kotlin.String? = null,

    @SerialName(value = "pricingDetails") val pricingDetails: kotlin.String? = null,

    @SerialName(value = "pricingDescription") val pricingDescription: kotlin.String? = null,

    @SerialName(value = "howItWorks") val howItWorks: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "operationRestrictions") val operationRestrictions: OperationRestrictions? = null

)
