/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param product
 * @param pickupEta
 * @param surgeInfo
 * @param discountInfo
 */
@Serializable
data class RideHailingProductWithEta(

    @SerialName(value = "product") @Required val product: RideHailingProduct,

    @SerialName(value = "pickupEta") val pickupEta: Eta? = null,

    @SerialName(value = "surgeInfo") val surgeInfo: SurgeInfo? = null,

    @SerialName(value = "discountInfo") val discountInfo: DiscountInfo? = null

)
