/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param options
 * @param providersWithRequirements
 * @param offerDurationSeconds
 * @param offerTimeoutSeconds
 */
@Serializable
data class RideHailingOptionsResponse(

    @SerialName(value = "options") @Required val options: kotlin.collections.List<RideHailingOption>,

    @SerialName(value = "providersWithRequirements") @Required val providersWithRequirements: kotlin.collections.List<ProviderWithRequirements>,

    @SerialName(value = "offerDurationSeconds") @Required val offerDurationSeconds: kotlin.Long,

    @SerialName(value = "offerTimeoutSeconds") val offerTimeoutSeconds: kotlin.Int? = null

)
