/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Part of the route for shared transport
 *
 * @param provider
 * @param segmentName
 * @param vehicle
 * @param startStation
 * @param endStation
 * @param gearboxText
 * @param pricingText
 * @param rangeRemaining
 */
@Serializable
data class RouteSegmentSharing(

    @SerialName(value = "provider") @Required val provider: Provider,

    @SerialName(value = "segmentName") @Required val segmentName: kotlin.String,

    @SerialName(value = "vehicle") val vehicle: SharedVehicle? = null,

    @SerialName(value = "startStation") val startStation: RouteSegmentSharingStation? = null,

    @SerialName(value = "endStation") val endStation: RouteSegmentSharingStation? = null,

    @SerialName(value = "gearboxText") val gearboxText: kotlin.String? = null,

    @SerialName(value = "pricingText") val pricingText: kotlin.String? = null,

    @SerialName(value = "rangeRemaining") val rangeRemaining: kotlin.String? = null

)
