/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param frequencySeconds
 * @param fromTime
 * @param toTime
 * @param tags
 */
@Serializable
data class RouteIntervalDeparture(

    @SerialName(value = "frequencySeconds") @Required val frequencySeconds: kotlin.Int,

    @SerialName(value = "fromTime") @Required val fromTime: kotlin.String,

    @SerialName(value = "toTime") @Required val toTime: kotlin.String,

    @SerialName(value = "tags") @Required val tags: kotlin.collections.List<kotlin.String>

)
