/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Request to assign category to feedback entry
 *
 * @param resultId Associated route result id
 * @param feedbackEntryId Unique routes feedback entry ID
 * @param categoryId Category id
 */
@Serializable
data class RoutesFeedbackAddCategoryRequest(

    /* Associated route result id */
    @SerialName(value = "resultId") @Required val resultId: kotlin.String,

    /* Unique routes feedback entry ID */
    @SerialName(value = "feedbackEntryId") @Required val feedbackEntryId: kotlin.String,

    /* Category id */
    @SerialName(value = "categoryId") @Required val categoryId: kotlin.String

)
