/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param name
 * @param vehicleType
 * @param location
 * @param address
 * @param freeSpots
 * @param vehicleCount
 */
@Serializable
data class RouteSegmentSharingStation(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "vehicleType") @Required val vehicleType: VehicleType,

    @SerialName(value = "location") @Required val location: LatLng,

    @SerialName(value = "address") val address: kotlin.String? = null,

    @SerialName(value = "freeSpots") val freeSpots: kotlin.Int? = null,

    @SerialName(value = "vehicleCount") val vehicleCount: kotlin.Int? = null

)
