/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param mode
 * @param start
 * @param end
 * @param startTime
 * @param endTime
 * @param shape Shape, or path, of the segment, encoded using Google polyline encoding format !:https://developers.google.com/maps/documentation/utilities/polylinealgorithm
 * @param intervalStartTime
 * @param intervalEndTime
 * @param transit
 * @param walking
 * @param sharing
 * @param rideHailing
 * @param personalVehicle
 * @param fareId
 * @param disruption
 */
@Serializable
data class RouteSegment(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "mode") @Required val mode: RouteSegmentMode,

    @SerialName(value = "start") @Required val start: Location,

    @SerialName(value = "end") @Required val end: Location,

    @SerialName(value = "startTime") @Required val startTime: kotlin.String,

    @SerialName(value = "endTime") @Required val endTime: kotlin.String,

    /* Shape, or path, of the segment, encoded using Google polyline encoding format !:https://developers.google.com/maps/documentation/utilities/polylinealgorithm */
    @SerialName(value = "shape") @Required val shape: kotlin.String,

    @SerialName(value = "intervalStartTime") val intervalStartTime: TimeInterval? = null,

    @SerialName(value = "intervalEndTime") val intervalEndTime: TimeInterval? = null,

    @SerialName(value = "transit") val transit: RouteSegmentTransit? = null,

    @SerialName(value = "walking") val walking: RouteSegmentWalking? = null,

    @SerialName(value = "sharing") val sharing: RouteSegmentSharing? = null,

    @SerialName(value = "rideHailing") val rideHailing: RouteSegmentRideHailing? = null,

    @SerialName(value = "personalVehicle") val personalVehicle: RouteSegmentPersonalVehicle? = null,

    @SerialName(value = "fareId") val fareId: kotlin.String? = null,

    @SerialName(value = "disruption") val disruption: RouteSegmentDisruption? = null

)
