/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param time ISO 8601 date and time of the departure, including the offset from UTC, e.g. \"2018-06-14T10:15:00+02:00\"
 * @param isRealtime
 * @param tags
 * @param vehicleId
 */
@Serializable
data class RouteExactDeparture(

    /* ISO 8601 date and time of the departure, including the offset from UTC, e.g. \"2018-06-14T10:15:00+02:00\" */
    @SerialName(value = "time") @Required val time: kotlin.String,

    @SerialName(value = "isRealtime") @Required val isRealtime: kotlin.Boolean,

    @SerialName(value = "tags") @Required val tags: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "vehicleId") val vehicleId: kotlin.String? = null

)
