/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param isAccessible
 * @param segments
 * @param startTime
 * @param endTime
 * @param duration
 * @param isAvailable
 * @param firstTransitSegmentExactDepartures
 * @param sustainability
 * @param groupId
 * @param fare
 * @param intervalEndTime
 * @param labelKey
 * @param disruption
 */
@Serializable
data class Route(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "isAccessible") @Required val isAccessible: kotlin.Boolean,

    @SerialName(value = "segments") @Required val segments: kotlin.collections.List<RouteSegment>,

    @SerialName(value = "startTime") @Required val startTime: kotlin.String,

    @SerialName(value = "endTime") @Required val endTime: kotlin.String,

    @SerialName(value = "duration") @Required val duration: IntervalDuration,

    @SerialName(value = "isAvailable") @Required val isAvailable: kotlin.Boolean,

    @SerialName(value = "firstTransitSegmentExactDepartures") @Required val firstTransitSegmentExactDepartures: kotlin.collections.List<RouteExactDeparture>,

    @SerialName(value = "sustainability") @Required val sustainability: SustainabilityProperties,

    @SerialName(value = "groupId") val groupId: kotlin.String? = null,

    @SerialName(value = "fare") val fare: RouteFare? = null,

    @SerialName(value = "intervalEndTime") val intervalEndTime: TimeInterval? = null,

    @SerialName(value = "labelKey") val labelKey: kotlin.String? = null,

    @SerialName(value = "disruption") val disruption: RouteDisruption? = null

)
