/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Initial route feedback request, with a positive or a negative rating
 *
 * @param resultId Associated route result id
 * @param isPositive
 */
@Serializable
data class RoutesFeedbackRateRequest(

    /* Associated route result id */
    @SerialName(value = "resultId") @Required val resultId: kotlin.String,

    @SerialName(value = "isPositive") val isPositive: kotlin.Boolean? = null

)
