/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param total
 * @param fares An array of `Fare` objects representing different fares that comprise the `Total`
 */
@Serializable
data class RouteFare(

    @SerialName(value = "total") @Required val total: Money,

    /* An array of `Fare` objects representing different fares that comprise the `Total` */
    @SerialName(value = "fares") @Required val fares: kotlin.collections.List<Fare>

)
