/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param provider
 * @param productId
 * @param isSharedRide
 * @param productDisplayName
 * @param seatCount
 * @param waitTime
 * @param priceText
 * @param surgeMultiplierText
 */
@Serializable
data class RouteSegmentRideHailing(

    @SerialName(value = "provider") @Required val provider: Provider,

    @SerialName(value = "productId") @Required val productId: kotlin.String,

    @SerialName(value = "isSharedRide") @Required val isSharedRide: kotlin.Boolean,

    @SerialName(value = "productDisplayName") @Required val productDisplayName: kotlin.String,

    @SerialName(value = "seatCount") val seatCount: kotlin.Int? = null,

    @SerialName(value = "waitTime") val waitTime: kotlin.Long? = null,

    @SerialName(value = "priceText") val priceText: kotlin.String? = null,

    @SerialName(value = "surgeMultiplierText") val surgeMultiplierText: kotlin.String? = null

)
