/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param schedule
 * @param stop
 * @param now
 * @param extendedExactDepartures
 * @param extendedIntervalDepartures
 * @param track
 */
@Serializable
data class ScheduleWithStopWithDepartures(

    @SerialName(value = "schedule") @Required val schedule: Schedule,

    @SerialName(value = "stop") @Required val stop: Stop,

    @SerialName(value = "now") @Required val now: kotlin.String,

    @SerialName(value = "extendedExactDepartures") @Required val extendedExactDepartures: kotlin.collections.List<ExtendedExactDeparture>,

    @SerialName(value = "extendedIntervalDepartures") @Required val extendedIntervalDepartures: kotlin.collections.List<ExtendedIntervalDeparture>,

    @SerialName(value = "track") val track: Track? = null

)
