/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param scheduleId
 * @param trackId
 * @param direction
 */
@Serializable
data class ScheduleTrackDirectionItem(

    @SerialName(value = "scheduleId") @Required val scheduleId: kotlin.String,

    @SerialName(value = "trackId") @Required val trackId: kotlin.String,

    @SerialName(value = "direction") @Required val direction: TrackDirection

)
