/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param name Line number/name
 * @param color
 * @param transport
 * @param transportId
 * @param longName
 * @param textColor
 * @param transportType
 */
@Serializable
data class Schedule(

    @SerialName(value = "id") @Required val id: kotlin.String,

    /* Line number/name */
    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "color") @Required val color: kotlin.String,

    @SerialName(value = "transport") @Required val transport: Transport,

    @SerialName(value = "transportId") @Required val transportId: kotlin.String,

    @SerialName(value = "longName") val longName: kotlin.String? = null,

    @SerialName(value = "textColor") val textColor: kotlin.String? = null,

    @SerialName(value = "transportType") val transportType: kotlin.String? = null

)
