/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param location
 * @param id
 * @param serviceHoursText
 * @param phoneNumber
 * @param webUrl
 */
@Serializable
data class ServiceLocation(

    @SerialName(value = "location") @Required val location: Location,

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "serviceHoursText") val serviceHoursText: kotlin.String? = null,

    @SerialName(value = "phoneNumber") val phoneNumber: kotlin.String? = null,

    @SerialName(value = "webUrl") val webUrl: kotlin.String? = null

)
