/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param vehicleType
 * @param transportIcon
 * @param hasStations
 * @param vehicleSubtype
 * @param instantUnlockData
 * @param booking
 * @param vehicleSelection
 */
@Serializable
data class SharingProviderOptions(

    @SerialName(value = "vehicleType") @Required val vehicleType: VehicleType,

    @SerialName(value = "transportIcon") @Required val transportIcon: kotlin.String,

    @SerialName(value = "hasStations") @Required val hasStations: kotlin.Boolean,

    @SerialName(value = "vehicleSubtype") val vehicleSubtype: kotlin.String? = null,

    @SerialName(value = "instantUnlockData") val instantUnlockData: InstantUnlockData? = null,

    @SerialName(value = "booking") val booking: SharingBookingOptions? = null,

    @SerialName(value = "vehicleSelection") val vehicleSelection: SharingVehicleSelectionOptions? = null

)
