/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param provider
 * @param status
 * @param currency
 * @param timeElapsedSeconds
 * @param currentTime
 * @param priceBreakdowns
 * @param fuelCards
 * @param paymentMethodId
 * @param tripPurposeId
 * @param price
 * @param timeRemainingSeconds
 * @param distanceMeters
 * @param startTime
 * @param finishTime
 * @param startLocationTitle
 * @param startLocation
 * @param finishLocationTitle
 * @param finishLocation
 * @param vehicle
 * @param prompt
 * @param feedbackId
 * @param purchaseBreakdown
 * @param notes
 */
@Serializable
data class SharingBooking(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "provider") @Required val provider: Provider,

    @SerialName(value = "status") @Required val status: SharingBookingStatus,

    @SerialName(value = "currency") @Required val currency: kotlin.String,

    @SerialName(value = "timeElapsedSeconds") @Required val timeElapsedSeconds: kotlin.Long,

    @SerialName(value = "currentTime") @Required val currentTime: kotlin.Long,

    @SerialName(value = "priceBreakdowns") @Required val priceBreakdowns: kotlin.collections.List<PriceBreakdown>,

    @SerialName(value = "fuelCards") @Required val fuelCards: kotlin.collections.List<FuelCard>,

    @SerialName(value = "paymentMethodId") val paymentMethodId: kotlin.String? = null,

    @SerialName(value = "tripPurposeId") val tripPurposeId: kotlin.String? = null,

    @SerialName(value = "price") val price: kotlin.Double? = null,

    @SerialName(value = "timeRemainingSeconds") val timeRemainingSeconds: kotlin.Long? = null,

    @SerialName(value = "distanceMeters") val distanceMeters: kotlin.Long? = null,

    @SerialName(value = "startTime") val startTime: kotlin.Long? = null,

    @SerialName(value = "finishTime") val finishTime: kotlin.Long? = null,

    @SerialName(value = "startLocationTitle") val startLocationTitle: kotlin.String? = null,

    @SerialName(value = "startLocation") val startLocation: LatLng? = null,

    @SerialName(value = "finishLocationTitle") val finishLocationTitle: kotlin.String? = null,

    @SerialName(value = "finishLocation") val finishLocation: LatLng? = null,

    @SerialName(value = "vehicle") val vehicle: SharedVehicle? = null,

    @SerialName(value = "prompt") val prompt: BookingPrompt? = null,

    @SerialName(value = "feedbackId") val feedbackId: kotlin.String? = null,

    @SerialName(value = "purchaseBreakdown") val purchaseBreakdown: PurchaseBreakdown? = null,

    @SerialName(value = "notes") val notes: kotlin.collections.List<Note>? = null

)
