/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param providers
 * @param vehicles
 * @param vehicleGroups
 * @param zones
 * @param zoneTypes
 * @param providerPaymentMethods
 */
@Serializable
data class SharingNearbyResponse(

    @SerialName(value = "providers") @Required val providers: kotlin.collections.List<Provider>,

    @SerialName(value = "vehicles") @Required val vehicles: kotlin.collections.List<SharedVehicle>,

    @SerialName(value = "vehicleGroups") @Required val vehicleGroups: kotlin.collections.List<VehicleGroup>,

    @SerialName(value = "zones") @Required val zones: kotlin.collections.List<Zone>,

    @SerialName(value = "zoneTypes") @Required val zoneTypes: kotlin.collections.List<ZoneType>,

    @SerialName(value = "providerPaymentMethods") @Required val providerPaymentMethods: kotlin.collections.List<ProviderPaymentMethods>

)
