/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param northEast
 * @param southWest
 * @param providerIds Comma separated list.
 * @param vehicleType
 * @param categoryId
 */
@Serializable
data class SharingMapRequest(

    @SerialName(value = "northEast") @Required val northEast: LatLng,

    @SerialName(value = "southWest") @Required val southWest: LatLng,

    /* Comma separated list. */
    @SerialName(value = "providerIds") @Required val providerIds: kotlin.String,

    @SerialName(value = "vehicleType") val vehicleType: VehicleType? = null,

    @SerialName(value = "categoryId") val categoryId: kotlin.String? = null

)
