/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param allowedActions
 * @param requiresVehicleCode
 * @param requiresLocationOnCreateBooking
 * @param requiresLocationOnFinishBooking
 * @param requiresPhotoOnFinishBooking
 * @param requiresDriverLicenseConfirmationForLegalReasons
 * @param requiresHelmetConfirmationForLegalReasons
 * @param paidReservation
 */
@Serializable
data class SharingBookingOptions(

    @SerialName(value = "allowedActions") @Required val allowedActions: kotlin.collections.List<SharingAllowedAction>,

    @SerialName(value = "requiresVehicleCode") val requiresVehicleCode: kotlin.Boolean? = null,

    @SerialName(value = "requiresLocationOnCreateBooking") val requiresLocationOnCreateBooking: kotlin.Boolean? = null,

    @SerialName(value = "requiresLocationOnFinishBooking") val requiresLocationOnFinishBooking: kotlin.Boolean? = null,

    @SerialName(value = "requiresPhotoOnFinishBooking") val requiresPhotoOnFinishBooking: kotlin.Boolean? = null,

    @SerialName(value = "requiresDriverLicenseConfirmationForLegalReasons") val requiresDriverLicenseConfirmationForLegalReasons: kotlin.Boolean? = null,

    @SerialName(value = "requiresHelmetConfirmationForLegalReasons") val requiresHelmetConfirmationForLegalReasons: kotlin.Boolean? = null,

    @SerialName(value = "paidReservation") val paidReservation: kotlin.Boolean? = null

)
