/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param providerId
 * @param location
 * @param tags
 * @param endLeaseSupported
 * @param reservationSupported
 * @param parkingSupported
 * @param requiresUserLocation
 * @param type
 * @param sustainability
 * @param stationId
 * @param name
 * @param address
 * @param licencePlate
 * @param pricing
 * @param imageUrl
 * @param battery
 * @param fuel
 * @param rangeRemaining
 * @param deepLinkIos
 * @param deepLinkAndroid
 * @param localizations
 * @param pin
 * @param subtype
 */
@Serializable
data class SharedVehicle(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "providerId") @Required val providerId: kotlin.String,

    @SerialName(value = "location") @Required val location: LatLng,

    @SerialName(value = "tags") @Required val tags: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "endLeaseSupported") @Required val endLeaseSupported: kotlin.Boolean,

    @SerialName(value = "reservationSupported") @Required val reservationSupported: kotlin.Boolean,

    @SerialName(value = "parkingSupported") @Required val parkingSupported: kotlin.Boolean,

    @SerialName(value = "requiresUserLocation") @Required val requiresUserLocation: kotlin.Boolean,

    @SerialName(value = "type") @Required val type: VehicleType,

    @SerialName(value = "sustainability") @Required val sustainability: SustainabilityProperties,

    @SerialName(value = "stationId") val stationId: kotlin.String? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "address") val address: kotlin.String? = null,

    @SerialName(value = "licencePlate") val licencePlate: kotlin.String? = null,

    @SerialName(value = "pricing") val pricing: VehiclePricing? = null,

    @SerialName(value = "imageUrl") val imageUrl: kotlin.String? = null,

    @SerialName(value = "battery") val battery: Battery? = null,

    @SerialName(value = "fuel") val fuel: Fuel? = null,

    @SerialName(value = "rangeRemaining") val rangeRemaining: kotlin.Int? = null,

    @SerialName(value = "deepLinkIos") val deepLinkIos: DeepLink? = null,

    @SerialName(value = "deepLinkAndroid") val deepLinkAndroid: DeepLink? = null,

    @SerialName(value = "localizations") val localizations: VehicleSharingLocalizations? = null,

    @SerialName(value = "pin") val pin: Pin? = null,

    @SerialName(value = "subtype") val subtype: kotlin.String? = null

)
