/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param vehicleId
 * @param providerId
 * @param qrCode
 * @param publicId
 * @param initialBookingAction
 * @param providerPaymentMethodId
 * @param paymentMethodId
 * @param tripPurposeId
 * @param messagingToken
 * @param userLocation
 * @param braintreeDeviceData
 */
@Serializable
data class StartSharingReservationRequest(

    @SerialName(value = "vehicleId") @Required val vehicleId: kotlin.String,

    @SerialName(value = "providerId") val providerId: kotlin.String? = null,

    @SerialName(value = "qrCode") val qrCode: kotlin.String? = null,

    @SerialName(value = "publicId") val publicId: kotlin.String? = null,

    @SerialName(value = "initialBookingAction") val initialBookingAction: SharingBookingAction? = null,

    @SerialName(value = "providerPaymentMethodId") val providerPaymentMethodId: kotlin.String? = null,

    @SerialName(value = "paymentMethodId") val paymentMethodId: kotlin.String? = null,

    @SerialName(value = "tripPurposeId") val tripPurposeId: kotlin.String? = null,

    @SerialName(value = "messagingToken") val messagingToken: kotlin.String? = null,

    @SerialName(value = "userLocation") val userLocation: LatLng? = null,

    @SerialName(value = "braintreeDeviceData") val braintreeDeviceData: kotlin.String? = null

)
