/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param bounds
 * @param transportIds Comma separated transportIds
 * @param activeSchedulesOnly
 * @param namePrefix Filter stops whose name starts with the given prefix
 * @param nameInfix Filter stops whose name contains the given infix
 * @param stopIds Comma separated stopIds
 * @param subregionId Subregion id, e.g., bern
 */
@Serializable
data class StopFilter(

    @SerialName(value = "bounds") val bounds: PlatformLatLngBounds? = null,

    /* Comma separated transportIds */
    @SerialName(value = "transportIds") val transportIds: kotlin.String? = null,

    @SerialName(value = "activeSchedulesOnly") val activeSchedulesOnly: kotlin.Boolean? = null,

    /* Filter stops whose name starts with the given prefix */
    @SerialName(value = "namePrefix") val namePrefix: kotlin.String? = null,

    /* Filter stops whose name contains the given infix */
    @SerialName(value = "nameInfix") val nameInfix: kotlin.String? = null,

    /* Comma separated stopIds */
    @SerialName(value = "stopIds") val stopIds: kotlin.String? = null,

    /* Subregion id, e.g., bern */
    @SerialName(value = "subregionId") val subregionId: kotlin.String? = null

)
