/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param stop
 * @param now
 * @param scheduleDepartures
 * @param walkPath
 */
@Serializable
data class StopWithSchedulesWithDepartures(

    @SerialName(value = "stop") @Required val stop: Stop,

    @SerialName(value = "now") @Required val now: kotlin.String,

    @SerialName(value = "scheduleDepartures") @Required val scheduleDepartures: kotlin.collections.List<ScheduleWithDepartures>,

    @SerialName(value = "walkPath") val walkPath: WalkPath? = null

)
