/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param name
 * @param regionId
 * @param location
 * @param type
 * @param children
 * @param exits
 * @param transports
 * @param transportIds
 * @param address
 * @param direction
 * @param parentId
 * @param zoneId
 * @param platformCode
 * @param platformName
 */
@Serializable
data class Stop(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "regionId") @Required val regionId: kotlin.String,

    @SerialName(value = "location") @Required val location: LatLng,

    @SerialName(value = "type") @Required val type: StopType,

    @SerialName(value = "children") @Required val children: kotlin.collections.List<Stop>,

    @SerialName(value = "exits") @Required val exits: kotlin.collections.List<Stop>,

    @SerialName(value = "transports") @Required val transports: kotlin.collections.List<TransportIcon>,

    @SerialName(value = "transportIds") @Required val transportIds: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "address") val address: kotlin.String? = null,

    @SerialName(value = "direction") val direction: kotlin.String? = null,

    @SerialName(value = "parentId") val parentId: kotlin.String? = null,

    @SerialName(value = "zoneId") val zoneId: kotlin.String? = null,

    @SerialName(value = "platformCode") val platformCode: kotlin.String? = null,

    @SerialName(value = "platformName") val platformName: kotlin.String? = null

)
