/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param providers
 * @param supportedProviders
 * @param iconName
 * @param remaining
 */
@Serializable
data class SubscriptionProviderBenefit(

    @SerialName(value = "providers") @Required val providers: kotlin.collections.List<SubscriptionSharingProvider>,

    @SerialName(value = "supportedProviders") @Required val supportedProviders: kotlin.collections.List<SubscriptionProvider>,

    @SerialName(value = "iconName") @Required val iconName: kotlin.String,

    @SerialName(value = "remaining") @Required val remaining: SubscriptionRemainder

)
