/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param plans
 * @param title
 * @param description
 * @param empty
 * @param about
 * @param howItWorks
 */
@Serializable
data class SubscriptionPlansResponse(

    @SerialName(value = "plans") @Required val plans: kotlin.collections.List<SubscriptionPlan>,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "empty") val empty: SubscriptionEmpty? = null,

    @SerialName(value = "about") val about: SubscriptionAbout? = null,

    @SerialName(value = "howItWorks") val howItWorks: SubscriptionHowItWorks? = null

)
