/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param label
 * @param phoneNumber
 * @param email
 */
@Serializable
data class SupportInfo(

    @SerialName(value = "label") @Required val label: kotlin.String,

    @SerialName(value = "phoneNumber") @Required val phoneNumber: kotlin.String,

    @SerialName(value = "email") val email: kotlin.String? = null

)
