/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param multiplier
 * @param confirmationUrl
 * @param multiplierText
 */
@Serializable
data class SurgeInfo(

    @SerialName(value = "multiplier") @Required val multiplier: kotlin.Double,

    @SerialName(value = "confirmationUrl") val confirmationUrl: kotlin.String? = null,

    @SerialName(value = "multiplierText") val multiplierText: kotlin.String? = null

)
