/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param name
 * @param detailsHeader
 * @param detailsItems
 */
@Serializable
data class SustainabilitySourceDetails(

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "detailsHeader") @Required val detailsHeader: kotlin.String,

    @SerialName(value = "detailsItems") @Required val detailsItems: kotlin.collections.List<kotlin.String>

)
