/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param numberOfSeats
 * @param gearboxType
 * @param fuelType
 * @param driveType
 * @param engineSpec
 * @param consumptionLitersPer100Km
 * @param consumptionKwhPer100Km
 * @param energyEfficiency
 * @param co2GramsPerKm
 * @param trailerHitchPossible
 * @param kidSeatsAvailable
 * @param airConditioning
 * @param bluetooth
 * @param hasUsbConnection
 * @param auxParking
 */
@Serializable
data class TechnicalData(

    @SerialName(value = "numberOfSeats") val numberOfSeats: kotlin.Int? = null,

    @SerialName(value = "gearboxType") val gearboxType: VehicleGearbox? = null,

    @SerialName(value = "fuelType") val fuelType: VehicleFuel? = null,

    @SerialName(value = "driveType") val driveType: VehicleDrive? = null,

    @SerialName(value = "engineSpec") val engineSpec: kotlin.String? = null,

    @SerialName(value = "consumptionLitersPer100Km") val consumptionLitersPer100Km: kotlin.Double? = null,

    @SerialName(value = "consumptionKwhPer100Km") val consumptionKwhPer100Km: kotlin.Double? = null,

    @SerialName(value = "energyEfficiency") val energyEfficiency: kotlin.String? = null,

    @SerialName(value = "co2GramsPerKm") val co2GramsPerKm: kotlin.Double? = null,

    @SerialName(value = "trailerHitchPossible") val trailerHitchPossible: kotlin.Boolean? = null,

    @SerialName(value = "kidSeatsAvailable") val kidSeatsAvailable: kotlin.Boolean? = null,

    @SerialName(value = "airConditioning") val airConditioning: kotlin.Boolean? = null,

    @SerialName(value = "bluetooth") val bluetooth: kotlin.Boolean? = null,

    @SerialName(value = "hasUsbConnection") val hasUsbConnection: kotlin.Boolean? = null,

    @SerialName(value = "auxParking") val auxParking: kotlin.Boolean? = null

)
