/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param key
 * @param type
 * @param titleText
 * @param accepted
 * @param acceptedByDefault
 * @param version
 * @param required
 * @param implicit
 * @param title
 * @param descriptionText
 * @param lastActionAtMillis
 * @param lastInteractedVersion
 * @param placeholder
 * @param url
 */
@Serializable
data class Term(

    @SerialName(value = "key") @Required val key: kotlin.String,

    @SerialName(value = "type") @Required val type: TermType,

    @SerialName(value = "titleText") @Required val titleText: TermText,

    @SerialName(value = "accepted") @Required val accepted: kotlin.Boolean,

    @SerialName(value = "acceptedByDefault") @Required val acceptedByDefault: kotlin.Boolean,

    @SerialName(value = "version") @Required val version: kotlin.String,

    @SerialName(value = "required") @Required val required: kotlin.Boolean,

    @SerialName(value = "implicit") @Required val implicit: kotlin.Boolean,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "descriptionText") val descriptionText: TermText? = null,

    @SerialName(value = "lastActionAtMillis") val lastActionAtMillis: kotlin.Long? = null,

    @SerialName(value = "lastInteractedVersion") val lastInteractedVersion: kotlin.String? = null,

    @SerialName(value = "placeholder") val placeholder: kotlin.String? = null,

    @SerialName(value = "url") val url: kotlin.String? = null

)
