/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param url
 * @param rangeStart
 * @param rangeEnd
 */
@Serializable
data class TextUrlSpan(

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "rangeStart") @Required val rangeStart: kotlin.Int,

    @SerialName(value = "rangeEnd") @Required val rangeEnd: kotlin.Int

)
