/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param productId
 * @param validTicketCount
 * @param buyTicketCount
 * @param providerId
 * @param userOfferContext
 * @param validFromMillis
 * @param validFromOffset
 * @param departureStopId
 */
@Serializable
data class TicketBuyRequestItem(

    @SerialName(value = "productId") @Required val productId: kotlin.String,

    @SerialName(value = "validTicketCount") @Required val validTicketCount: kotlin.Int,

    @SerialName(value = "buyTicketCount") @Required val buyTicketCount: kotlin.Int,

    @SerialName(value = "providerId") val providerId: kotlin.String? = null,

    @SerialName(value = "userOfferContext") val userOfferContext: kotlin.String? = null,

    @SerialName(value = "validFromMillis") val validFromMillis: kotlin.Long? = null,

    @SerialName(value = "validFromOffset") val validFromOffset: kotlin.Long? = null,

    @SerialName(value = "departureStopId") val departureStopId: kotlin.String? = null

)
