/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param items
 * @param idempotencyKey
 * @param braintreeDeviceData
 * @param paymentMethodId
 * @param tripPurposeId
 */
@Serializable
data class TicketBuyRequest(

    @SerialName(value = "items") @Required val items: kotlin.collections.List<TicketBuyRequestItem>,

    @SerialName(value = "idempotencyKey") val idempotencyKey: kotlin.String? = null,

    @SerialName(value = "braintreeDeviceData") val braintreeDeviceData: kotlin.String? = null,

    @SerialName(value = "paymentMethodId") val paymentMethodId: kotlin.String? = null,

    @SerialName(value = "tripPurposeId") val tripPurposeId: kotlin.String? = null

)
