/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param currentTime
 * @param tickets
 * @param ticketSubscriptions
 * @param providers
 */
@Serializable
data class TicketsResponse(

    @SerialName(value = "currentTime") @Required val currentTime: kotlin.Long,

    @SerialName(value = "tickets") @Required val tickets: kotlin.collections.List<Ticket>,

    @SerialName(value = "ticketSubscriptions") @Required val ticketSubscriptions: kotlin.collections.List<TicketSubscription>,

    @SerialName(value = "providers") @Required val providers: kotlin.collections.List<Provider>

)
