/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param min
 * @param initial
 * @param max
 */
@Serializable
data class TicketProductActivationArgument(

    @SerialName(value = "min") @Required val min: kotlin.Int,

    @SerialName(value = "initial") @Required val initial: kotlin.Int,

    @SerialName(value = "max") @Required val max: kotlin.Int

)
