/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param status
 * @param currentTime
 * @param currentTicket
 * @param expiresAt not null if Whitelabel.App.Contract.TicketsV2.TicketSubscription.Status == Canceled
 * @param renewsOn not null if Whitelabel.App.Contract.TicketsV2.TicketSubscription.Status == Active
 */
@Serializable
data class TicketSubscription(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "status") @Required val status: TicketSubscriptionStatus,

    @SerialName(value = "currentTime") @Required val currentTime: kotlin.Long,

    @SerialName(value = "currentTicket") val currentTicket: Ticket? = null,

    /* not null if Whitelabel.App.Contract.TicketsV2.TicketSubscription.Status == Canceled */
    @SerialName(value = "expiresAt") val expiresAt: kotlin.Long? = null,

    /* not null if Whitelabel.App.Contract.TicketsV2.TicketSubscription.Status == Active */
    @SerialName(value = "renewsOn") val renewsOn: kotlin.Long? = null

)
