/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param onlyImmediately
 * @param includeTime
 * @param maxDaysInAdvance
 * @param messages
 * @param minDaysInAdvance
 */
@Serializable
data class TicketProductDateArgument(

    @SerialName(value = "onlyImmediately") @Required val onlyImmediately: kotlin.Boolean,

    @SerialName(value = "includeTime") @Required val includeTime: kotlin.Boolean,

    @SerialName(value = "maxDaysInAdvance") @Required val maxDaysInAdvance: kotlin.Int,

    @SerialName(value = "messages") @Required val messages: kotlin.collections.List<InfoMessage>,

    @SerialName(value = "minDaysInAdvance") val minDaysInAdvance: kotlin.Int? = null

)
