/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param providers
 * @param categories
 * @param popular
 * @param other
 * @param ticketSubscriptions
 * @param provider
 * @param supportsGettingTicketsByRoute
 * @param subregionId
 */
@Serializable
data class TicketProductResponse(

    @SerialName(value = "providers") @Required val providers: kotlin.collections.List<Provider>,

    @SerialName(value = "categories") @Required val categories: kotlin.collections.List<TicketProductCategory>,

    @SerialName(value = "popular") @Required val popular: kotlin.collections.List<TicketProductGroup>,

    @SerialName(value = "other") @Required val other: kotlin.collections.List<TicketProductGroup>,

    @SerialName(value = "ticketSubscriptions") @Required val ticketSubscriptions: kotlin.collections.List<TicketProductGroup>,

    @SerialName(value = "provider") val provider: Provider? = null,

    @SerialName(value = "supportsGettingTicketsByRoute") val supportsGettingTicketsByRoute: kotlin.Boolean? = null,

    @SerialName(value = "subregionId") val subregionId: kotlin.String? = null

)
