/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param name
 * @param originalName
 * @param description
 * @param iconType
 * @param isPopular
 * @param products
 * @param subtitle
 * @param suffix
 * @param resources
 * @param isForBoardingOnly
 * @param providerId
 */
@Serializable
data class TicketProductGroup(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "originalName") @Required val originalName: kotlin.String,

    @SerialName(value = "description") @Required val description: kotlin.String,

    @SerialName(value = "iconType") @Required val iconType: IconType,

    @SerialName(value = "isPopular") @Required val isPopular: kotlin.Boolean,

    @SerialName(value = "products") @Required val products: kotlin.collections.List<TicketProduct>,

    @SerialName(value = "subtitle") val subtitle: kotlin.String? = null,

    @SerialName(value = "suffix") val suffix: kotlin.String? = null,

    @SerialName(value = "resources") val resources: ProductGroupResources? = null,

    @SerialName(value = "isForBoardingOnly") val isForBoardingOnly: kotlin.Boolean? = null,

    @SerialName(value = "providerId") val providerId: kotlin.String? = null

)
