/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param price
 * @param currency
 * @param messages
 * @param properties
 * @param providerId
 * @param userOfferContext
 * @param information
 * @param tags
 * @param arguments
 * @param maxBuyProductItemCount
 */
@Serializable
data class TicketProduct(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "price") @Required val price: kotlin.Double,

    @SerialName(value = "currency") @Required val currency: kotlin.String,

    @SerialName(value = "messages") @Required val messages: kotlin.collections.List<InfoMessage>,

    @SerialName(value = "properties") @Required val properties: kotlin.collections.List<TicketProductProperty>,

    @SerialName(value = "providerId") @Required val providerId: kotlin.String,

    @SerialName(value = "userOfferContext") val userOfferContext: kotlin.String? = null,

    @SerialName(value = "information") val information: kotlin.String? = null,

    @SerialName(value = "tags") val tags: kotlin.collections.List<Tag>? = null,

    @SerialName(value = "arguments") val arguments: TicketProductArguments? = null,

    @SerialName(value = "maxBuyProductItemCount") val maxBuyProductItemCount: kotlin.Int? = null

)
