/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param name
 * @param originalName
 * @param iconType
 * @param groups
 * @param description
 * @param providerId
 */
@Serializable
data class TicketProductCategory(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "originalName") @Required val originalName: kotlin.String,

    @SerialName(value = "iconType") @Required val iconType: IconType,

    @SerialName(value = "groups") @Required val groups: kotlin.collections.List<TicketProductGroup>,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "providerId") val providerId: kotlin.String? = null

)
