/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param weekdaysId
 * @param weekdays
 * @param exactTimes
 * @param intervalTimes
 */
@Serializable
data class Times(

    @SerialName(value = "weekdaysId") @Required val weekdaysId: kotlin.Int,

    @SerialName(value = "weekdays") @Required val weekdays: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "exactTimes") @Required val exactTimes: kotlin.collections.List<ExactTime>,

    @SerialName(value = "intervalTimes") @Required val intervalTimes: kotlin.collections.List<IntervalTime>

)
