/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param providerId
 * @param cardId
 * @param amount
 */
@Serializable
data class TopUpTravelCardRequest(

    @SerialName(value = "providerId") @Required val providerId: kotlin.String,

    @SerialName(value = "cardId") @Required val cardId: kotlin.String,

    @SerialName(value = "amount") @Required val amount: kotlin.Double

)
