/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param track
 * @param exactDepartures
 * @param intervalDepartures
 * @param disruption
 */
@Serializable
data class TrackWithDepartures(

    @SerialName(value = "track") @Required val track: Track,

    @SerialName(value = "exactDepartures") @Required val exactDepartures: kotlin.collections.List<ExactDeparture>,

    @SerialName(value = "intervalDepartures") @Required val intervalDepartures: kotlin.collections.List<IntervalDeparture>,

    @SerialName(value = "disruption") val disruption: TrackWithDeparturesDisruption? = null

)
