/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param destination
 * @param name
 * @param shape
 * @param direction
 * @param visible
 */
@Serializable
data class Track(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "destination") @Required val destination: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "shape") @Required val shape: kotlin.String,

    @SerialName(value = "direction") @Required val direction: TrackDirection,

    @SerialName(value = "visible") @Required val visible: kotlin.Boolean

)
