/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*

/**
 *
 *
 * @param position
 * @param schedule
 * @param track
 */
@Serializable
data class TransitVehiclePositionWithScheduleAndTrack(

    @SerialName(value = "position") @Required val position: TransitVehiclePosition,

    @SerialName(value = "schedule") @Required val schedule: Schedule,

    @SerialName(value = "track") @Required val track: Track

)
