/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import com.trafi.core.model.TransitTrip

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param realtimeResponseId 
 * @param trip 
 */
@Serializable
data class TransitTripResponse (

    @SerialName(value = "realtimeResponseId") @Required val realtimeResponseId: kotlin.String,

    @SerialName(value = "trip") @Required val trip: TransitTrip

)

