/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param vehicleId
 * @param location
 * @param trackShapeMovementFractionalIndices
 * @param trackStopFraction
 * @param angle
 * @param trackShape
 * @param timestamp
 */
@Serializable
data class TransitVehiclePosition(

    @SerialName(value = "vehicleId") @Required val vehicleId: kotlin.String,

    @SerialName(value = "location") @Required val location: LatLng,

    @SerialName(value = "trackShapeMovementFractionalIndices") @Required val trackShapeMovementFractionalIndices: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "trackStopFraction") val trackStopFraction: kotlin.Double? = null,

    @SerialName(value = "angle") val angle: kotlin.Double? = null,

    @SerialName(value = "trackShape") val trackShape: kotlin.String? = null,

    @SerialName(value = "timestamp") val timestamp: kotlin.Long? = null

)
