/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param secondsAfterMidnight
 * @param isRealtime
 * @param timeLabel
 */
@Serializable
data class TransitTripExactTime(

    @SerialName(value = "secondsAfterMidnight") @Required val secondsAfterMidnight: kotlin.Int,

    @SerialName(value = "isRealtime") @Required val isRealtime: kotlin.Boolean,

    @SerialName(value = "timeLabel") val timeLabel: kotlin.String? = null

)
