/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param providerId
 * @param status
 * @param id
 * @param cardNumber
 * @param currency
 * @param cardTypeId Provider specific card type, e.q:       for RB - basic, plus, plus_adulto , plus_discapacidad
 * @param cardTypeText
 * @param holder
 * @param balance
 * @param pendingAmount
 * @param balanceText
 * @param balanceDateText
 */
@Serializable
data class TravelCard(

    @SerialName(value = "providerId") @Required val providerId: kotlin.String,

    @SerialName(value = "status") @Required val status: TravelCardStatus,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "cardNumber") @Required val cardNumber: kotlin.String,

    @SerialName(value = "currency") @Required val currency: kotlin.String,

    /* Provider specific card type, e.q:       for RB - basic, plus, plus_adulto , plus_discapacidad */
    @SerialName(value = "cardTypeId") val cardTypeId: kotlin.String? = null,

    @SerialName(value = "cardTypeText") val cardTypeText: kotlin.String? = null,

    @SerialName(value = "holder") val holder: TravelCardHolder? = null,

    @SerialName(value = "balance") val balance: kotlin.Double? = null,

    @SerialName(value = "pendingAmount") val pendingAmount: kotlin.Double? = null,

    @SerialName(value = "balanceText") val balanceText: kotlin.String? = null,

    @SerialName(value = "balanceDateText") val balanceDateText: kotlin.String? = null

)
