/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param terms
 * @param termKeys
 * @param installId Id unique per app installation
 * @param deviceId Id unique per device, i.e. Android device id or iOS IDFV
 * @param advertisingId Advertising id, i.e. Android GAID or iOS IDFA
 */
@Serializable
data class UpdatePlatformTerms(

    @SerialName(value = "terms") @Required val terms: kotlin.collections.List<VersionedTerm>,

    @SerialName(value = "termKeys") val termKeys: kotlin.collections.List<kotlin.String>? = null,

    /* Id unique per app installation */
    @SerialName(value = "installId") val installId: kotlin.String? = null,

    /* Id unique per device, i.e. Android device id or iOS IDFV */
    @SerialName(value = "deviceId") val deviceId: kotlin.String? = null,

    /* Advertising id, i.e. Android GAID or iOS IDFA */
    @SerialName(value = "advertisingId") val advertisingId: kotlin.String? = null

)
