/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param providerId
 * @param bookingId
 * @param dropoff
 * @param paymentConfirmation
 */
@Serializable
data class UpdateRideHailingBookingRequest(

    @SerialName(value = "providerId") @Required val providerId: kotlin.String,

    @SerialName(value = "bookingId") @Required val bookingId: kotlin.String,

    @SerialName(value = "dropoff") val dropoff: Location? = null,

    @SerialName(value = "paymentConfirmation") val paymentConfirmation: PaymentConfirmation? = null

)
