/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*

/**
 * Import execution result
 *
 * Values: UNKNOWN,USER_NOT_FOUND,EXECUTED,ALREADY_IMPORTED,EXECUTION_FAILED
 */
@Serializable
enum class UserImportResult(val value: kotlin.String) {

    @SerialName(value = "UNKNOWN")
    UNKNOWN("UNKNOWN"),

    @SerialName(value = "USER_NOT_FOUND")
    USER_NOT_FOUND("USER_NOT_FOUND"),

    @SerialName(value = "EXECUTED")
    EXECUTED("EXECUTED"),

    @SerialName(value = "ALREADY_IMPORTED")
    ALREADY_IMPORTED("ALREADY_IMPORTED"),

    @SerialName(value = "EXECUTION_FAILED")
    EXECUTION_FAILED("EXECUTION_FAILED");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is UserImportResult) "$data" else null

        /**
         * Returns a valid [UserImportResult] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): UserImportResult? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
