/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param personalDetails
 * @param phoneNumber
 * @param paymentMethod
 * @param drivingLicence
 * @param identity
 * @param memberships
 * @param addressDetails
 */
@Serializable
data class UserRequirements(

    @SerialName(value = "personalDetails") @Required val personalDetails: Requirement,

    @SerialName(value = "phoneNumber") @Required val phoneNumber: Requirement,

    @SerialName(value = "paymentMethod") @Required val paymentMethod: Requirement,

    @SerialName(value = "drivingLicence") @Required val drivingLicence: Requirement,

    @SerialName(value = "identity") @Required val identity: Requirement,

    @SerialName(value = "memberships") @Required val memberships: kotlin.collections.List<Requirement>,

    @SerialName(value = "addressDetails") val addressDetails: Requirement? = null

)
