/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param profile
 * @param providerAccounts
 * @param drivingLicence
 * @param identity
 * @param paymentMethods
 * @param requirements
 * @param memberships
 * @param createdAt
 * @param providerAccountIntents
 * @param restrictedProviders
 * @param phoneNumber
 */
@Serializable
data class User(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "profile") @Required val profile: Profile,

    @SerialName(value = "providerAccounts") @Required val providerAccounts: kotlin.collections.List<ProviderAccount>,

    @SerialName(value = "drivingLicence") @Required val drivingLicence: DrivingLicence,

    @SerialName(value = "identity") @Required val identity: Identity,

    @SerialName(value = "paymentMethods") @Required val paymentMethods: kotlin.collections.List<PaymentMethod>,

    @SerialName(value = "requirements") @Required val requirements: UserRequirements,

    @SerialName(value = "memberships") @Required val memberships: kotlin.collections.List<Membership>,

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.String,

    @SerialName(value = "providerAccountIntents") @Required val providerAccountIntents: kotlin.collections.List<ProviderAccountIntent>,

    @SerialName(value = "restrictedProviders") @Required val restrictedProviders: kotlin.collections.List<RestrictedProvider>,

    @SerialName(value = "phoneNumber") val phoneNumber: kotlin.String? = null

)
