/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param loginAndReserveButtonTitle
 * @param reserveButtonTitle
 * @param reservingButtonTitle
 * @param startLeaseButtonTitle
 * @param startingLeaseButtonTitle
 * @param startLeaseConfirmationTitle
 * @param startLeaseConfirmationButtonTitle
 * @param endLeaseButtonTitle
 * @param endingLeaseButtonTitle
 * @param endLeaseConfirmationTitle
 * @param endLeaseConfirmationButtonTitle
 * @param startedLeaseInfoTitle
 * @param startedLeaseInfoBody
 * @param startedLeaseInformationTitle
 */
@Serializable
data class VehicleSharingLocalizations(

    @SerialName(value = "loginAndReserveButtonTitle") @Required val loginAndReserveButtonTitle: kotlin.String,

    @SerialName(value = "reserveButtonTitle") @Required val reserveButtonTitle: kotlin.String,

    @SerialName(value = "reservingButtonTitle") @Required val reservingButtonTitle: kotlin.String,

    @SerialName(value = "startLeaseButtonTitle") @Required val startLeaseButtonTitle: kotlin.String,

    @SerialName(value = "startingLeaseButtonTitle") @Required val startingLeaseButtonTitle: kotlin.String,

    @SerialName(value = "startLeaseConfirmationTitle") @Required val startLeaseConfirmationTitle: kotlin.String,

    @SerialName(value = "startLeaseConfirmationButtonTitle") @Required val startLeaseConfirmationButtonTitle: kotlin.String,

    @SerialName(value = "endLeaseButtonTitle") @Required val endLeaseButtonTitle: kotlin.String,

    @SerialName(value = "endingLeaseButtonTitle") @Required val endingLeaseButtonTitle: kotlin.String,

    @SerialName(value = "endLeaseConfirmationTitle") @Required val endLeaseConfirmationTitle: kotlin.String,

    @SerialName(value = "endLeaseConfirmationButtonTitle") @Required val endLeaseConfirmationButtonTitle: kotlin.String,

    @SerialName(value = "startedLeaseInfoTitle") val startedLeaseInfoTitle: kotlin.String? = null,

    @SerialName(value = "startedLeaseInfoBody") val startedLeaseInfoBody: kotlin.String? = null,

    @SerialName(value = "startedLeaseInformationTitle") val startedLeaseInformationTitle: kotlin.String? = null

)
