/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param providerId
 * @param sessionId
 * @param baseUrl
 * @param sessionToken
 * @param type
 */
@Serializable
data class VerificationResponse(

    @SerialName(value = "providerId") @Required val providerId: kotlin.String,

    @SerialName(value = "sessionId") @Required val sessionId: kotlin.String,

    @SerialName(value = "baseUrl") @Required val baseUrl: kotlin.String,

    @SerialName(value = "sessionToken") @Required val sessionToken: kotlin.String,

    @SerialName(value = "type") @Required val type: VerificationDocumentType

)
