/**
 * Core Whitelabel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.trafi.core.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param id
 * @param providerId
 * @param vehicleType
 * @param shape
 * @param holes
 * @param isReturnAllowed
 * @param color
 * @param name
 * @param priority
 * @param returnFee
 * @param currency
 * @param zoneTypeId
 */
@Serializable
data class Zone(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "providerId") @Required val providerId: kotlin.String,

    @SerialName(value = "vehicleType") @Required val vehicleType: VehicleType,

    @SerialName(value = "shape") @Required val shape: kotlin.String,

    @SerialName(value = "holes") @Required val holes: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "isReturnAllowed") @Required val isReturnAllowed: kotlin.Boolean,

    @SerialName(value = "color") @Required val color: kotlin.String,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "priority") val priority: kotlin.Int? = null,

    @SerialName(value = "returnFee") val returnFee: kotlin.Double? = null,

    @SerialName(value = "currency") val currency: kotlin.String? = null,

    @SerialName(value = "zoneTypeId") val zoneTypeId: kotlin.String? = null

)
