name: Build Android
on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: ktlint
        if: always()
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: ktlintCheck
      - name: Lint
        if: always()
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: lint
      - name: Retain lint artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lint
          path: android/**/build/reports/lint-results.html
      - name: Test
        if: always()
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test
      - name: Assemble
        if: always()
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assemble
